# Code generated by contracts/codegen.py. DO NOT EDIT.
"""Canonical telemetry contract, generated from contracts/schema/messages_v1.yaml.

Timestamps are int microseconds since the Unix epoch, UTC; 0 means unset.
Use ``ts_to_dt`` / ``dt_to_ts`` rather than converting by hand.
"""
from __future__ import annotations

from dataclasses import dataclass, field, fields as dc_fields
from datetime import datetime, timezone
from enum import IntEnum
from typing import Any


def ts_to_dt(us: int) -> datetime | None:
    """Contract microseconds -> aware UTC datetime (None when unset)."""
    if not us:
        return None
    return datetime.fromtimestamp(us / 1_000_000, tz=timezone.utc)


def dt_to_ts(dt: datetime | None) -> int:
    """Aware datetime -> contract microseconds (0 when None)."""
    if dt is None:
        return 0
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return int(dt.timestamp() * 1_000_000)


class Protocol(IntEnum):
    UNSPECIFIED = 0
    SNMP = 1
    SNMP_TRAP = 2
    GNMI = 3
    BACNET = 4
    REDFISH = 5
    MODBUS = 6
    SFLOW = 7


class ValueType(IntEnum):
    UNSPECIFIED = 0
    GAUGE = 1
    COUNTER = 2
    DELTA = 3
    BOOL = 4
    TEXT = 5


class Quality(IntEnum):
    UNSPECIFIED = 0
    GOOD = 1
    STALE = 2
    SUSPECT = 3
    BAD = 4
    NO_DATA = 5


class Severity(IntEnum):
    UNSPECIFIED = 0
    CLEAR = 1
    INFO = 2
    WARNING = 3
    MINOR = 4
    MAJOR = 5
    CRITICAL = 6


class CommStatus(IntEnum):
    UNSPECIFIED = 0
    ONLINE = 1
    DEGRADED = 2
    OFFLINE = 3
    UNKNOWN = 4
    DISABLED = 5


class _Msg:
    """Mixin: msgpack-map codec keyed by field name, tolerant of unknown keys."""

    def to_dict(self) -> dict[str, Any]:
        out: dict[str, Any] = {}
        for f in dc_fields(self):
            v = getattr(self, f.name)
            if v in (None, 0, 0.0, '', False) or (isinstance(v, (dict, list)) and not v):
                continue  # omitempty, matching the Go encoder
            if isinstance(v, list):
                out[f.name] = [i.to_dict() if hasattr(i, 'to_dict') else i for i in v]
            elif hasattr(v, 'to_dict'):
                out[f.name] = v.to_dict()
            else:
                out[f.name] = int(v) if isinstance(v, IntEnum) else v
        return out

    @classmethod
    def from_dict(cls, d: dict[str, Any]):
        kwargs: dict[str, Any] = {}
        nested = getattr(cls, '_nested', {})
        for f in dc_fields(cls):
            if f.name not in d:
                continue  # absent == default; forward compatible
            v = d[f.name]
            sub = nested.get(f.name)
            if sub is not None and isinstance(v, list):
                v = [sub.from_dict(i) if isinstance(i, dict) else i for i in v]
            kwargs[f.name] = v
        return cls(**kwargs)


@dataclass(slots=True)
class Telemetry(_Msg):
    """One observation of one metric on one instance of one device."""
    endpoint_id: str = ""
    device_id: str = ""
    metric: str = ""
    instance: str = ""
    value_type: int = 0
    double_value: float = 0.0
    uint_value: int = 0
    bool_value: bool = False
    text_value: str = ""
    unit: str = ""
    observed_at: int = 0
    collected_at: int = 0
    source_protocol: int = 0
    quality: int = 0
    counter_reset: bool = False
    counter_bits: int = 0
    metadata: dict[str, str] = field(default_factory=dict)


@dataclass(slots=True)
class TelemetryBatch(_Msg):
    """What actually goes on the wire; per-sample framing is wasteful."""
    collector_id: str = ""
    samples: list["Telemetry"] = field(default_factory=list)
    sent_at: int = 0
    schema_version: int = 0
    trace_id: str = ""

    _nested = {"samples": Telemetry}


@dataclass(slots=True)
class Event(_Msg):
    """A discrete state-change notification - SNMP trap, Redfish event, BACnet COV."""
    endpoint_id: str = ""
    device_id: str = ""
    source_ip: str = ""
    event_type: str = ""
    instance: str = ""
    severity: int = 0
    is_clear: bool = False
    message: str = ""
    observed_at: int = 0
    collected_at: int = 0
    source_protocol: int = 0
    varbinds: dict[str, str] = field(default_factory=dict)
    raw_identifier: str = ""
    dedup_key: str = ""
    metric: str = ""
    value: float = 0.0
    threshold: float = 0.0


@dataclass(slots=True)
class EventBatch(_Msg):
    collector_id: str = ""
    events: list["Event"] = field(default_factory=list)
    sent_at: int = 0
    schema_version: int = 0
    trace_id: str = ""

    _nested = {"events": Event}


@dataclass(slots=True)
class EndpointState(_Msg):
    """Published immediately on every status change, and periodically for endpoints whose status has NOT changed. The periodic copy exists because liveness is a property of the poll, not of the data: with change-only publishing, 894 healthy endpoints sat with last_success eleven hours old while polling perfectly, and poll_count was never written at all. is_refresh separates the two - a refresh updates the liveness columns and counters and nothing else, so it must not raise alarms, re-derive device status, or push a websocket update.
"""
    endpoint_id: str = ""
    device_id: str = ""
    collector_id: str = ""
    status: int = 0
    last_success: int = 0
    last_failure: int = 0
    consecutive_failures: int = 0
    last_error: str = ""
    last_error_class: str = ""
    latency_ms: int = 0
    changed_at: int = 0
    is_refresh: bool = False
    last_seen: int = 0
    poll_count: int = 0
    fail_count: int = 0
    timeout_count: int = 0
    auth_fail_count: int = 0


@dataclass(slots=True)
class CollectorHeartbeat(_Msg):
    collector_id: str = ""
    version: str = ""
    hostname: str = ""
    started_at: int = 0
    sent_at: int = 0
    endpoints_owned: int = 0
    endpoints_online: int = 0
    polls_total: int = 0
    polls_failed: int = 0
    traps_received: int = 0
    events_received: int = 0
    queue_depth: int = 0
    active_streams: int = 0
    assignment_version: int = 0
    config_version: int = 0
    config_restart_pending: bool = False
    config_error: str = ""


class Stream:
    """Redis stream names and caps."""

    TELEMETRY = "telemetry.v1"
    EVENTS = "events.v1"
    ENDPOINTSTATE = "endpointstate.v1"
    HEARTBEAT = "collectorhb.v1"


STREAM_MAXLEN = {
    "telemetry.v1": 8000,
    "events.v1": 200000,
    "endpointstate.v1": 100000,
    "collectorhb.v1": 10000,
}

SCHEMA_VERSION = 1
