// Code generated by contracts/codegen.py. DO NOT EDIT.

package models

// Contract version 1 (dcim.telemetry.v1).
// Timestamps are int64 microseconds since the Unix epoch, UTC; 0 means unset.

type Protocol int32

const (
	ProtocolUnspecified Protocol = 0
	ProtocolSNMP        Protocol = 1
	ProtocolSNMPTrap    Protocol = 2
	ProtocolGNMI        Protocol = 3
	ProtocolBacnet      Protocol = 4
	ProtocolRedfish     Protocol = 5
	ProtocolModbus      Protocol = 6
	ProtocolSflow       Protocol = 7
)

var protocolNames = map[Protocol]string{
	0: "UNSPECIFIED",
	1: "SNMP",
	2: "SNMP_TRAP",
	3: "GNMI",
	4: "BACNET",
	5: "REDFISH",
	6: "MODBUS",
	7: "SFLOW",
}

func (e Protocol) String() string {
	if s, ok := protocolNames[e]; ok {
		return s
	}
	return "UNSPECIFIED"
}

type ValueType int32

const (
	ValueTypeUnspecified ValueType = 0
	ValueTypeGauge       ValueType = 1
	ValueTypeCounter     ValueType = 2
	ValueTypeDelta       ValueType = 3
	ValueTypeBool        ValueType = 4
	ValueTypeText        ValueType = 5
)

var valuetypeNames = map[ValueType]string{
	0: "UNSPECIFIED",
	1: "GAUGE",
	2: "COUNTER",
	3: "DELTA",
	4: "BOOL",
	5: "TEXT",
}

func (e ValueType) String() string {
	if s, ok := valuetypeNames[e]; ok {
		return s
	}
	return "UNSPECIFIED"
}

type Quality int32

const (
	QualityUnspecified Quality = 0
	QualityGood        Quality = 1
	QualityStale       Quality = 2
	QualitySuspect     Quality = 3
	QualityBad         Quality = 4
	QualityNoData      Quality = 5
)

var qualityNames = map[Quality]string{
	0: "UNSPECIFIED",
	1: "GOOD",
	2: "STALE",
	3: "SUSPECT",
	4: "BAD",
	5: "NO_DATA",
}

func (e Quality) String() string {
	if s, ok := qualityNames[e]; ok {
		return s
	}
	return "UNSPECIFIED"
}

type Severity int32

const (
	SeverityUnspecified Severity = 0
	SeverityClear       Severity = 1
	SeverityInfo        Severity = 2
	SeverityWarning     Severity = 3
	SeverityMinor       Severity = 4
	SeverityMajor       Severity = 5
	SeverityCritical    Severity = 6
)

var severityNames = map[Severity]string{
	0: "UNSPECIFIED",
	1: "CLEAR",
	2: "INFO",
	3: "WARNING",
	4: "MINOR",
	5: "MAJOR",
	6: "CRITICAL",
}

func (e Severity) String() string {
	if s, ok := severityNames[e]; ok {
		return s
	}
	return "UNSPECIFIED"
}

type CommStatus int32

const (
	CommStatusUnspecified CommStatus = 0
	CommStatusOnline      CommStatus = 1
	CommStatusDegraded    CommStatus = 2
	CommStatusOffline     CommStatus = 3
	CommStatusUnknown     CommStatus = 4
	CommStatusDisabled    CommStatus = 5
)

var commstatusNames = map[CommStatus]string{
	0: "UNSPECIFIED",
	1: "ONLINE",
	2: "DEGRADED",
	3: "OFFLINE",
	4: "UNKNOWN",
	5: "DISABLED",
}

func (e CommStatus) String() string {
	if s, ok := commstatusNames[e]; ok {
		return s
	}
	return "UNSPECIFIED"
}

// Telemetry - One observation of one metric on one instance of one device.
type Telemetry struct {
	EndpointID     string            `msgpack:"endpoint_id,omitempty" json:"endpoint_id,omitempty"` // DCIM device_endpoint.id - the authoritative identity
	DeviceID       string            `msgpack:"device_id,omitempty" json:"device_id,omitempty"`     // DCIM device.id, carried so ingest needs no join
	Metric         string            `msgpack:"metric,omitempty" json:"metric,omitempty"`           // canonical metric key from the registry
	Instance       string            `msgpack:"instance,omitempty" json:"instance,omitempty"`       // ifIndex / sensor id / phase / object instance; empty = device-scoped
	ValueType      ValueType         `msgpack:"value_type,omitempty" json:"value_type,omitempty"`
	DoubleValue    float64           `msgpack:"double_value,omitempty" json:"double_value,omitempty"`
	UintValue      uint64            `msgpack:"uint_value,omitempty" json:"uint_value,omitempty"` // counters - full 64-bit, no float precision loss
	BoolValue      bool              `msgpack:"bool_value,omitempty" json:"bool_value,omitempty"`
	TextValue      string            `msgpack:"text_value,omitempty" json:"text_value,omitempty"`
	Unit           string            `msgpack:"unit,omitempty" json:"unit,omitempty"`
	ObservedAt     int64             `msgpack:"observed_at,omitempty" json:"observed_at,omitempty"`   // device/protocol time where available
	CollectedAt    int64             `msgpack:"collected_at,omitempty" json:"collected_at,omitempty"` // collector wall clock
	SourceProtocol Protocol          `msgpack:"source_protocol,omitempty" json:"source_protocol,omitempty"`
	Quality        Quality           `msgpack:"quality,omitempty" json:"quality,omitempty"`
	CounterReset   bool              `msgpack:"counter_reset,omitempty" json:"counter_reset,omitempty"` // true => discard the delta across this sample
	CounterBits    uint32            `msgpack:"counter_bits,omitempty" json:"counter_bits,omitempty"`   // 32 or 64, for wrap arithmetic
	Metadata       map[string]string `msgpack:"metadata,omitempty" json:"metadata,omitempty"`           // protocol provenance, DEBUG ONLY - never branch on it
}

// TelemetryBatch - What actually goes on the wire; per-sample framing is wasteful.
type TelemetryBatch struct {
	CollectorID   string      `msgpack:"collector_id,omitempty" json:"collector_id,omitempty"`
	Samples       []Telemetry `msgpack:"samples,omitempty" json:"samples,omitempty"`
	SentAt        int64       `msgpack:"sent_at,omitempty" json:"sent_at,omitempty"`
	SchemaVersion uint32      `msgpack:"schema_version,omitempty" json:"schema_version,omitempty"`
	TraceID       string      `msgpack:"trace_id,omitempty" json:"trace_id,omitempty"`
}

// Event - A discrete state-change notification - SNMP trap, Redfish event, BACnet COV.
type Event struct {
	EndpointID     string            `msgpack:"endpoint_id,omitempty" json:"endpoint_id,omitempty"`
	DeviceID       string            `msgpack:"device_id,omitempty" json:"device_id,omitempty"`   // empty if the source could not be resolved
	SourceIP       string            `msgpack:"source_ip,omitempty" json:"source_ip,omitempty"`   // always populated - the fallback identity
	EventType      string            `msgpack:"event_type,omitempty" json:"event_type,omitempty"` // canonical, e.g. link_down
	Instance       string            `msgpack:"instance,omitempty" json:"instance,omitempty"`
	Severity       Severity          `msgpack:"severity,omitempty" json:"severity,omitempty"`
	IsClear        bool              `msgpack:"is_clear,omitempty" json:"is_clear,omitempty"` // true => clears the alarm with the same key
	Message        string            `msgpack:"message,omitempty" json:"message,omitempty"`
	ObservedAt     int64             `msgpack:"observed_at,omitempty" json:"observed_at,omitempty"`
	CollectedAt    int64             `msgpack:"collected_at,omitempty" json:"collected_at,omitempty"`
	SourceProtocol Protocol          `msgpack:"source_protocol,omitempty" json:"source_protocol,omitempty"`
	Varbinds       map[string]string `msgpack:"varbinds,omitempty" json:"varbinds,omitempty"`
	RawIdentifier  string            `msgpack:"raw_identifier,omitempty" json:"raw_identifier,omitempty"` // trap OID / Redfish MessageId / BACnet object ref
	DedupKey       string            `msgpack:"dedup_key,omitempty" json:"dedup_key,omitempty"`
	Metric         string            `msgpack:"metric,omitempty" json:"metric,omitempty"`       // metric key the notification is about, if any
	Value          float64           `msgpack:"value,omitempty" json:"value,omitempty"`         // the reading the device reported
	Threshold      float64           `msgpack:"threshold,omitempty" json:"threshold,omitempty"` // the limit the device says it crossed
}

type EventBatch struct {
	CollectorID   string  `msgpack:"collector_id,omitempty" json:"collector_id,omitempty"`
	Events        []Event `msgpack:"events,omitempty" json:"events,omitempty"`
	SentAt        int64   `msgpack:"sent_at,omitempty" json:"sent_at,omitempty"`
	SchemaVersion uint32  `msgpack:"schema_version,omitempty" json:"schema_version,omitempty"`
	TraceID       string  `msgpack:"trace_id,omitempty" json:"trace_id,omitempty"`
}

// EndpointState - Published immediately on every status change, and periodically for endpoints whose status has NOT changed. The periodic copy exists because liveness is a property of the poll, not of the data: with change-only publishing, 894 healthy endpoints sat with last_success eleven hours old while polling perfectly, and poll_count was never written at all. is_refresh separates the two - a refresh updates the liveness columns and counters and nothing else, so it must not raise alarms, re-derive device status, or push a websocket update.

type EndpointState struct {
	EndpointID          string     `msgpack:"endpoint_id,omitempty" json:"endpoint_id,omitempty"`
	DeviceID            string     `msgpack:"device_id,omitempty" json:"device_id,omitempty"`
	CollectorID         string     `msgpack:"collector_id,omitempty" json:"collector_id,omitempty"`
	Status              CommStatus `msgpack:"status,omitempty" json:"status,omitempty"`
	LastSuccess         int64      `msgpack:"last_success,omitempty" json:"last_success,omitempty"`
	LastFailure         int64      `msgpack:"last_failure,omitempty" json:"last_failure,omitempty"`
	ConsecutiveFailures uint32     `msgpack:"consecutive_failures,omitempty" json:"consecutive_failures,omitempty"`
	LastError           string     `msgpack:"last_error,omitempty" json:"last_error,omitempty"`
	LastErrorClass      string     `msgpack:"last_error_class,omitempty" json:"last_error_class,omitempty"` // timeout|auth|refused|decode|unreachable|protocol
	LatencyMs           uint32     `msgpack:"latency_ms,omitempty" json:"latency_ms,omitempty"`
	ChangedAt           int64      `msgpack:"changed_at,omitempty" json:"changed_at,omitempty"`
	IsRefresh           bool       `msgpack:"is_refresh,omitempty" json:"is_refresh,omitempty"` // true => liveness only, status did not change
	LastSeen            int64      `msgpack:"last_seen,omitempty" json:"last_seen,omitempty"`   // last poll attempt, success or not
	PollCount           uint64     `msgpack:"poll_count,omitempty" json:"poll_count,omitempty"`
	FailCount           uint64     `msgpack:"fail_count,omitempty" json:"fail_count,omitempty"`
	TimeoutCount        uint64     `msgpack:"timeout_count,omitempty" json:"timeout_count,omitempty"`
	AuthFailCount       uint64     `msgpack:"auth_fail_count,omitempty" json:"auth_fail_count,omitempty"`
}

type CollectorHeartbeat struct {
	CollectorID          string `msgpack:"collector_id,omitempty" json:"collector_id,omitempty"`
	Version              string `msgpack:"version,omitempty" json:"version,omitempty"`
	Hostname             string `msgpack:"hostname,omitempty" json:"hostname,omitempty"`
	StartedAt            int64  `msgpack:"started_at,omitempty" json:"started_at,omitempty"`
	SentAt               int64  `msgpack:"sent_at,omitempty" json:"sent_at,omitempty"`
	EndpointsOwned       uint32 `msgpack:"endpoints_owned,omitempty" json:"endpoints_owned,omitempty"`
	EndpointsOnline      uint32 `msgpack:"endpoints_online,omitempty" json:"endpoints_online,omitempty"`
	PollsTotal           uint64 `msgpack:"polls_total,omitempty" json:"polls_total,omitempty"`
	PollsFailed          uint64 `msgpack:"polls_failed,omitempty" json:"polls_failed,omitempty"`
	TrapsReceived        uint64 `msgpack:"traps_received,omitempty" json:"traps_received,omitempty"`
	EventsReceived       uint64 `msgpack:"events_received,omitempty" json:"events_received,omitempty"`
	QueueDepth           uint32 `msgpack:"queue_depth,omitempty" json:"queue_depth,omitempty"`
	ActiveStreams        uint32 `msgpack:"active_streams,omitempty" json:"active_streams,omitempty"`
	AssignmentVersion    uint32 `msgpack:"assignment_version,omitempty" json:"assignment_version,omitempty"`
	ConfigVersion        uint32 `msgpack:"config_version,omitempty" json:"config_version,omitempty"`
	ConfigRestartPending bool   `msgpack:"config_restart_pending,omitempty" json:"config_restart_pending,omitempty"`
	ConfigError          string `msgpack:"config_error,omitempty" json:"config_error,omitempty"`
	ConfigEffective      string `msgpack:"config_effective,omitempty" json:"config_effective,omitempty"`
}

// Stream names and caps, from contracts/schema/messages_v1.yaml.
const (
	StreamTelemetry     = "telemetry.v1"
	StreamEvents        = "events.v1"
	StreamEndpointstate = "endpointstate.v1"
	StreamHeartbeat     = "collectorhb.v1"
)

var StreamMaxLen = map[string]int64{
	"telemetry.v1":     8000,
	"events.v1":        200000,
	"endpointstate.v1": 100000,
	"collectorhb.v1":   10000,
}

const SchemaVersion = 1
