// Code generated by contracts/codegen.py. DO NOT EDIT.

package models

// Canonical metric registry, generated from contracts/metrics/registry.yaml.
// A metric key absent from MetricDefs is a hard validation failure at emit time.

type MetricDef struct {
	Key         string
	DisplayName string
	Unit        string
	ValueType   string
	Aggregation string
	MinValid    float64
	MaxValid    float64
	HasMin      bool
	HasMax      bool
	StaleAfterS int
	Hot         bool
	Group       string
	RateOf      string
	RateScale   float64
}

const (
	MetricSysUptime          = "sys_uptime"
	MetricReachable          = "reachable"
	MetricPollLatency        = "poll_latency"
	MetricCPUUtilization     = "cpu_utilization"
	MetricCPUTemperature     = "cpu_temperature"
	MetricMemoryUtilization  = "memory_utilization"
	MetricMemoryUsed         = "memory_used"
	MetricMemoryTotal        = "memory_total"
	MetricMemoryAvailable    = "memory_available"
	MetricDiskUtilization    = "disk_utilization"
	MetricDiskUsed           = "disk_used"
	MetricDiskTotal          = "disk_total"
	MetricInletTemperature   = "inlet_temperature"
	MetricExhaustTemperature = "exhaust_temperature"
	MetricPowerDraw          = "power_draw"
	MetricIfAdminState       = "if_admin_state"
	MetricIfOperState        = "if_oper_state"
	MetricIfSpeed            = "if_speed"
	MetricIfInOctets         = "if_in_octets"
	MetricIfOutOctets        = "if_out_octets"
	MetricIfInBps            = "if_in_bps"
	MetricIfOutBps           = "if_out_bps"
	MetricIfInErrors         = "if_in_errors"
	MetricIfOutErrors        = "if_out_errors"
	MetricIfInDiscards       = "if_in_discards"
	MetricIfOutDiscards      = "if_out_discards"
	MetricIfInErrorRate      = "if_in_error_rate"
	MetricAmbientTemperature = "ambient_temperature"
	MetricRelativeHumidity   = "relative_humidity"
	MetricDewPoint           = "dew_point"
	MetricAirflow            = "airflow"
)

var MetricDefs = map[string]MetricDef{
	"sys_uptime": {
		Key: "sys_uptime", DisplayName: "System Uptime", Unit: "s",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "system", RateOf: "", RateScale: 1,
	},
	"reachable": {
		Key: "reachable", DisplayName: "Reachable", Unit: "bool",
		ValueType: "bool", Aggregation: "last",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: true,
		Group: "system", RateOf: "", RateScale: 1,
	},
	"poll_latency": {
		Key: "poll_latency", DisplayName: "Poll Latency", Unit: "ms",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 60000, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "system", RateOf: "", RateScale: 1,
	},
	"cpu_utilization": {
		Key: "cpu_utilization", DisplayName: "CPU Utilization", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"cpu_temperature": {
		Key: "cpu_temperature", DisplayName: "CPU Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "max",
		MinValid: -20, HasMin: true,
		MaxValid: 130, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "thermal", RateOf: "", RateScale: 1,
	},
	"memory_utilization": {
		Key: "memory_utilization", DisplayName: "Memory Utilization", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"memory_used": {
		Key: "memory_used", DisplayName: "Memory Used", Unit: "B",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 120, Hot: false,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"memory_total": {
		Key: "memory_total", DisplayName: "Memory Total", Unit: "B",
		ValueType: "gauge", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 3600, Hot: false,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"memory_available": {
		Key: "memory_available", DisplayName: "Memory Available", Unit: "B",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 120, Hot: false,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"disk_utilization": {
		Key: "disk_utilization", DisplayName: "Disk Utilization", Unit: "pct",
		ValueType: "gauge", Aggregation: "max",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"disk_used": {
		Key: "disk_used", DisplayName: "Disk Used", Unit: "B",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"disk_total": {
		Key: "disk_total", DisplayName: "Disk Total", Unit: "B",
		ValueType: "gauge", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 3600, Hot: false,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"inlet_temperature": {
		Key: "inlet_temperature", DisplayName: "Inlet Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "max",
		MinValid: -20, HasMin: true,
		MaxValid: 80, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "thermal", RateOf: "", RateScale: 1,
	},
	"exhaust_temperature": {
		Key: "exhaust_temperature", DisplayName: "Exhaust Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "max",
		MinValid: -20, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 120, Hot: false,
		Group: "thermal", RateOf: "", RateScale: 1,
	},
	"power_draw": {
		Key: "power_draw", DisplayName: "Power Draw", Unit: "W",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 50000, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"if_admin_state": {
		Key: "if_admin_state", DisplayName: "Interface Admin State", Unit: "bool",
		ValueType: "bool", Aggregation: "last",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_oper_state": {
		Key: "if_oper_state", DisplayName: "Interface Oper State", Unit: "bool",
		ValueType: "bool", Aggregation: "last",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_speed": {
		Key: "if_speed", DisplayName: "Interface Speed", Unit: "bps",
		ValueType: "gauge", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 3600, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_in_octets": {
		Key: "if_in_octets", DisplayName: "Interface In Octets", Unit: "B",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_out_octets": {
		Key: "if_out_octets", DisplayName: "Interface Out Octets", Unit: "B",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_in_bps": {
		Key: "if_in_bps", DisplayName: "Interface In Throughput", Unit: "bps",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "if_in_octets", RateScale: 8,
	},
	"if_out_bps": {
		Key: "if_out_bps", DisplayName: "Interface Out Throughput", Unit: "bps",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "if_out_octets", RateScale: 8,
	},
	"if_in_errors": {
		Key: "if_in_errors", DisplayName: "Interface In Errors", Unit: "count",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_out_errors": {
		Key: "if_out_errors", DisplayName: "Interface Out Errors", Unit: "count",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_in_discards": {
		Key: "if_in_discards", DisplayName: "Interface In Discards", Unit: "count",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_out_discards": {
		Key: "if_out_discards", DisplayName: "Interface Out Discards", Unit: "count",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_in_error_rate": {
		Key: "if_in_error_rate", DisplayName: "Interface In Error Rate", Unit: "count_per_s",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "if_in_errors", RateScale: 1,
	},
	"ambient_temperature": {
		Key: "ambient_temperature", DisplayName: "Ambient Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "max",
		MinValid: -40, HasMin: true,
		MaxValid: 90, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "environment", RateOf: "", RateScale: 1,
	},
	"relative_humidity": {
		Key: "relative_humidity", DisplayName: "Relative Humidity", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "environment", RateOf: "", RateScale: 1,
	},
	"dew_point": {
		Key: "dew_point", DisplayName: "Dew Point", Unit: "C",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: -40, HasMin: true,
		MaxValid: 60, HasMax: true,
		StaleAfterS: 120, Hot: false,
		Group: "environment", RateOf: "", RateScale: 1,
	},
	"airflow": {
		Key: "airflow", DisplayName: "Airflow", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 120, Hot: false,
		Group: "environment", RateOf: "", RateScale: 1,
	},
}

// MetricGroups maps a poll-profile group name to its metric keys.
var MetricGroups = map[string][]string{
	"compute":     {"cpu_utilization", "memory_utilization", "memory_used", "memory_total", "memory_available", "disk_utilization", "disk_used", "disk_total"},
	"environment": {"ambient_temperature", "relative_humidity", "dew_point", "airflow"},
	"interfaces":  {"if_admin_state", "if_oper_state", "if_speed", "if_in_octets", "if_out_octets", "if_in_bps", "if_out_bps", "if_in_errors", "if_out_errors", "if_in_discards", "if_out_discards", "if_in_error_rate"},
	"power":       {"power_draw"},
	"system":      {"sys_uptime", "reachable", "poll_latency"},
	"thermal":     {"cpu_temperature", "inlet_temperature", "exhaust_temperature"},
}
