// Code generated by contracts/codegen.py. DO NOT EDIT.

package models

// Canonical metric registry, generated from contracts/metrics/registry.yaml.
// A metric key absent from MetricDefs is a hard validation failure at emit time.

type MetricDef struct {
	Key         string
	DisplayName string
	Unit        string
	ValueType   string
	Aggregation string
	MinValid    float64
	MaxValid    float64
	HasMin      bool
	HasMax      bool
	StaleAfterS int
	Hot         bool
	Group       string
	RateOf      string
	RateScale   float64
}

const (
	MetricSysUptime            = "sys_uptime"
	MetricReachable            = "reachable"
	MetricPollLatency          = "poll_latency"
	MetricCPUUtilization       = "cpu_utilization"
	MetricCPUTemperature       = "cpu_temperature"
	MetricMemoryUtilization    = "memory_utilization"
	MetricMemoryUsed           = "memory_used"
	MetricMemoryTotal          = "memory_total"
	MetricMemoryAvailable      = "memory_available"
	MetricDiskUtilization      = "disk_utilization"
	MetricDiskUsed             = "disk_used"
	MetricDiskTotal            = "disk_total"
	MetricInletTemperature     = "inlet_temperature"
	MetricExhaustTemperature   = "exhaust_temperature"
	MetricPowerDraw            = "power_draw"
	MetricFanSpeed             = "fan_speed"
	MetricFanSpeedPct          = "fan_speed_pct"
	MetricPSUInputVoltage      = "psu_input_voltage"
	MetricPSUOutputPower       = "psu_output_power"
	MetricPSUState             = "psu_state"
	MetricEnergyConsumed       = "energy_consumed"
	MetricIfAdminState         = "if_admin_state"
	MetricIfOperState          = "if_oper_state"
	MetricIfSpeed              = "if_speed"
	MetricIfInOctets           = "if_in_octets"
	MetricIfOutOctets          = "if_out_octets"
	MetricIfInBps              = "if_in_bps"
	MetricIfOutBps             = "if_out_bps"
	MetricIfInErrors           = "if_in_errors"
	MetricIfOutErrors          = "if_out_errors"
	MetricIfInDiscards         = "if_in_discards"
	MetricIfOutDiscards        = "if_out_discards"
	MetricIfInErrorRate        = "if_in_error_rate"
	MetricAmbientTemperature   = "ambient_temperature"
	MetricRelativeHumidity     = "relative_humidity"
	MetricDewPoint             = "dew_point"
	MetricAirflow              = "airflow"
	MetricWaterSupplyTemp      = "water_supply_temp"
	MetricWaterReturnTemp      = "water_return_temp"
	MetricWaterSetpointTemp    = "water_setpoint_temp"
	MetricWaterFlow            = "water_flow"
	MetricWaterPressure        = "water_pressure"
	MetricWaterDiffPressure    = "water_diff_pressure"
	MetricValvePositionPct     = "valve_position_pct"
	MetricCompressorLoadPct    = "compressor_load_pct"
	MetricCoolingCapacity      = "cooling_capacity"
	MetricCoolingOutputPct     = "cooling_output_pct"
	MetricThermalLoad          = "thermal_load"
	MetricCop                  = "cop"
	MetricApproachTemp         = "approach_temp"
	MetricSupplyAirTemp        = "supply_air_temp"
	MetricReturnAirTemp        = "return_air_temp"
	MetricAirSetpointTemp      = "air_setpoint_temp"
	MetricFilterDiffPressure   = "filter_diff_pressure"
	MetricBasinLevelPct        = "basin_level_pct"
	MetricMakeupWaterFlow      = "makeup_water_flow"
	MetricVibration            = "vibration"
	MetricMotorTemp            = "motor_temp"
	MetricVfdFrequency         = "vfd_frequency"
	MetricPumpSpeedPct         = "pump_speed_pct"
	MetricRunHours             = "run_hours"
	MetricEquipmentState       = "equipment_state"
	MetricAlarmState           = "alarm_state"
	MetricVoltageLn            = "voltage_ln"
	MetricCurrent              = "current"
	MetricLineFrequency        = "line_frequency"
	MetricPowerFactor          = "power_factor"
	MetricVoltageThdPct        = "voltage_thd_pct"
	MetricCurrentThdPct        = "current_thd_pct"
	MetricHarmonicCurrentPct   = "harmonic_current_pct"
	MetricVoltageLl            = "voltage_ll"
	MetricReactivePower        = "reactive_power"
	MetricApparentPower        = "apparent_power"
	MetricLoadPct              = "load_pct"
	MetricPhaseImbalancePct    = "phase_imbalance_pct"
	MetricDemandPeakPower      = "demand_peak_power"
	MetricBatteryRuntime       = "battery_runtime"
	MetricBatteryHealthPct     = "battery_health_pct"
	MetricFuelLevelPct         = "fuel_level_pct"
	MetricCurrentRunTime       = "current_run_time"
	MetricStartAttempts        = "start_attempts"
	MetricTransferCount        = "transfer_count"
	MetricTimeOnEmergency      = "time_on_emergency"
	MetricOperatingMode        = "operating_mode"
	MetricComponentTemperature = "component_temperature"
)

var MetricDefs = map[string]MetricDef{
	"sys_uptime": {
		Key: "sys_uptime", DisplayName: "System Uptime", Unit: "s",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "system", RateOf: "", RateScale: 1,
	},
	"reachable": {
		Key: "reachable", DisplayName: "Reachable", Unit: "bool",
		ValueType: "bool", Aggregation: "last",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: true,
		Group: "system", RateOf: "", RateScale: 1,
	},
	"poll_latency": {
		Key: "poll_latency", DisplayName: "Poll Latency", Unit: "ms",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 60000, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "system", RateOf: "", RateScale: 1,
	},
	"cpu_utilization": {
		Key: "cpu_utilization", DisplayName: "CPU Utilization", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"cpu_temperature": {
		Key: "cpu_temperature", DisplayName: "CPU Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "max",
		MinValid: -20, HasMin: true,
		MaxValid: 130, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "thermal", RateOf: "", RateScale: 1,
	},
	"memory_utilization": {
		Key: "memory_utilization", DisplayName: "Memory Utilization", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"memory_used": {
		Key: "memory_used", DisplayName: "Memory Used", Unit: "B",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 120, Hot: false,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"memory_total": {
		Key: "memory_total", DisplayName: "Memory Total", Unit: "B",
		ValueType: "gauge", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 3600, Hot: false,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"memory_available": {
		Key: "memory_available", DisplayName: "Memory Available", Unit: "B",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 120, Hot: false,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"disk_utilization": {
		Key: "disk_utilization", DisplayName: "Disk Utilization", Unit: "pct",
		ValueType: "gauge", Aggregation: "max",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"disk_used": {
		Key: "disk_used", DisplayName: "Disk Used", Unit: "B",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"disk_total": {
		Key: "disk_total", DisplayName: "Disk Total", Unit: "B",
		ValueType: "gauge", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 3600, Hot: false,
		Group: "compute", RateOf: "", RateScale: 1,
	},
	"inlet_temperature": {
		Key: "inlet_temperature", DisplayName: "Inlet Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "max",
		MinValid: -20, HasMin: true,
		MaxValid: 80, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "thermal", RateOf: "", RateScale: 1,
	},
	"exhaust_temperature": {
		Key: "exhaust_temperature", DisplayName: "Exhaust Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "max",
		MinValid: -20, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 120, Hot: false,
		Group: "thermal", RateOf: "", RateScale: 1,
	},
	"power_draw": {
		Key: "power_draw", DisplayName: "Power Draw", Unit: "W",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 2e+07, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"fan_speed": {
		Key: "fan_speed", DisplayName: "Fan Speed", Unit: "rpm",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 30000, HasMax: true,
		StaleAfterS: 120, Hot: false,
		Group: "thermal", RateOf: "", RateScale: 1,
	},
	"fan_speed_pct": {
		Key: "fan_speed_pct", DisplayName: "Fan Speed Percent", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 120, Hot: false,
		Group: "thermal", RateOf: "", RateScale: 1,
	},
	"psu_input_voltage": {
		Key: "psu_input_voltage", DisplayName: "PSU Input Voltage", Unit: "V",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 600, HasMax: true,
		StaleAfterS: 120, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"psu_output_power": {
		Key: "psu_output_power", DisplayName: "PSU Output Power", Unit: "W",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 5000, HasMax: true,
		StaleAfterS: 120, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"psu_state": {
		Key: "psu_state", DisplayName: "PSU State", Unit: "bool",
		ValueType: "bool", Aggregation: "last",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"energy_consumed": {
		Key: "energy_consumed", DisplayName: "Energy Consumed", Unit: "kWh",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 600, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"if_admin_state": {
		Key: "if_admin_state", DisplayName: "Interface Admin State", Unit: "bool",
		ValueType: "bool", Aggregation: "last",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_oper_state": {
		Key: "if_oper_state", DisplayName: "Interface Oper State", Unit: "bool",
		ValueType: "bool", Aggregation: "last",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_speed": {
		Key: "if_speed", DisplayName: "Interface Speed", Unit: "bps",
		ValueType: "gauge", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 3600, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_in_octets": {
		Key: "if_in_octets", DisplayName: "Interface In Octets", Unit: "B",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_out_octets": {
		Key: "if_out_octets", DisplayName: "Interface Out Octets", Unit: "B",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_in_bps": {
		Key: "if_in_bps", DisplayName: "Interface In Throughput", Unit: "bps",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "if_in_octets", RateScale: 8,
	},
	"if_out_bps": {
		Key: "if_out_bps", DisplayName: "Interface Out Throughput", Unit: "bps",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "if_out_octets", RateScale: 8,
	},
	"if_in_errors": {
		Key: "if_in_errors", DisplayName: "Interface In Errors", Unit: "count",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_out_errors": {
		Key: "if_out_errors", DisplayName: "Interface Out Errors", Unit: "count",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_in_discards": {
		Key: "if_in_discards", DisplayName: "Interface In Discards", Unit: "count",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_out_discards": {
		Key: "if_out_discards", DisplayName: "Interface Out Discards", Unit: "count",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "", RateScale: 1,
	},
	"if_in_error_rate": {
		Key: "if_in_error_rate", DisplayName: "Interface In Error Rate", Unit: "count_per_s",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "interfaces", RateOf: "if_in_errors", RateScale: 1,
	},
	"ambient_temperature": {
		Key: "ambient_temperature", DisplayName: "Ambient Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "max",
		MinValid: -40, HasMin: true,
		MaxValid: 90, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "environment", RateOf: "", RateScale: 1,
	},
	"relative_humidity": {
		Key: "relative_humidity", DisplayName: "Relative Humidity", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 120, Hot: true,
		Group: "environment", RateOf: "", RateScale: 1,
	},
	"dew_point": {
		Key: "dew_point", DisplayName: "Dew Point", Unit: "C",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: -40, HasMin: true,
		MaxValid: 60, HasMax: true,
		StaleAfterS: 120, Hot: false,
		Group: "environment", RateOf: "", RateScale: 1,
	},
	"airflow": {
		Key: "airflow", DisplayName: "Airflow", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 120, Hot: false,
		Group: "environment", RateOf: "", RateScale: 1,
	},
	"water_supply_temp": {
		Key: "water_supply_temp", DisplayName: "Water Supply Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: -20, HasMin: true,
		MaxValid: 120, HasMax: true,
		StaleAfterS: 300, Hot: true,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"water_return_temp": {
		Key: "water_return_temp", DisplayName: "Water Return Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: -20, HasMin: true,
		MaxValid: 120, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"water_setpoint_temp": {
		Key: "water_setpoint_temp", DisplayName: "Water Setpoint", Unit: "C",
		ValueType: "gauge", Aggregation: "last",
		MinValid: -20, HasMin: true,
		MaxValid: 120, HasMax: true,
		StaleAfterS: 900, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"water_flow": {
		Key: "water_flow", DisplayName: "Water Flow", Unit: "L/s",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"water_pressure": {
		Key: "water_pressure", DisplayName: "Water Pressure", Unit: "kPa",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"water_diff_pressure": {
		Key: "water_diff_pressure", DisplayName: "Differential Pressure", Unit: "kPa",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"valve_position_pct": {
		Key: "valve_position_pct", DisplayName: "Valve Position", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"compressor_load_pct": {
		Key: "compressor_load_pct", DisplayName: "Compressor Load", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 300, Hot: true,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"cooling_capacity": {
		Key: "cooling_capacity", DisplayName: "Cooling Capacity", Unit: "W",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"cooling_output_pct": {
		Key: "cooling_output_pct", DisplayName: "Cooling Output", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"thermal_load": {
		Key: "thermal_load", DisplayName: "Thermal Load", Unit: "W",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"cop": {
		Key: "cop", DisplayName: "Coefficient of Performance", Unit: "ratio",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 20, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"approach_temp": {
		Key: "approach_temp", DisplayName: "Approach Temperature", Unit: "K",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"supply_air_temp": {
		Key: "supply_air_temp", DisplayName: "Supply Air Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: -20, HasMin: true,
		MaxValid: 80, HasMax: true,
		StaleAfterS: 300, Hot: true,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"return_air_temp": {
		Key: "return_air_temp", DisplayName: "Return Air Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: -20, HasMin: true,
		MaxValid: 80, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"air_setpoint_temp": {
		Key: "air_setpoint_temp", DisplayName: "Air Setpoint", Unit: "C",
		ValueType: "gauge", Aggregation: "last",
		MinValid: -20, HasMin: true,
		MaxValid: 80, HasMax: true,
		StaleAfterS: 900, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"filter_diff_pressure": {
		Key: "filter_diff_pressure", DisplayName: "Filter Differential Pressure", Unit: "kPa",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 600, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"basin_level_pct": {
		Key: "basin_level_pct", DisplayName: "Basin Level", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 600, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"makeup_water_flow": {
		Key: "makeup_water_flow", DisplayName: "Makeup Water Flow", Unit: "L/s",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 600, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"vibration": {
		Key: "vibration", DisplayName: "Vibration", Unit: "mm/s",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 600, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"motor_temp": {
		Key: "motor_temp", DisplayName: "Motor Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: -20, HasMin: true,
		MaxValid: 200, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"vfd_frequency": {
		Key: "vfd_frequency", DisplayName: "VFD Output Frequency", Unit: "Hz",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 200, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"pump_speed_pct": {
		Key: "pump_speed_pct", DisplayName: "Pump Speed", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"run_hours": {
		Key: "run_hours", DisplayName: "Run Hours", Unit: "h",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 3600, Hot: false,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"equipment_state": {
		Key: "equipment_state", DisplayName: "Equipment State", Unit: "bool",
		ValueType: "bool", Aggregation: "last",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: true,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"alarm_state": {
		Key: "alarm_state", DisplayName: "Alarm State", Unit: "bool",
		ValueType: "bool", Aggregation: "max",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: true,
		Group: "cooling", RateOf: "", RateScale: 1,
	},
	"voltage_ln": {
		Key: "voltage_ln", DisplayName: "Line-to-Neutral Voltage", Unit: "V",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 600, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"current": {
		Key: "current", DisplayName: "Current", Unit: "A",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: true,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"line_frequency": {
		Key: "line_frequency", DisplayName: "Line Frequency", Unit: "Hz",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"power_factor": {
		Key: "power_factor", DisplayName: "Power Factor", Unit: "ratio",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 1, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"voltage_thd_pct": {
		Key: "voltage_thd_pct", DisplayName: "Voltage THD", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 600, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"current_thd_pct": {
		Key: "current_thd_pct", DisplayName: "Current THD", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 600, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"harmonic_current_pct": {
		Key: "harmonic_current_pct", DisplayName: "Harmonic Current", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 600, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"voltage_ll": {
		Key: "voltage_ll", DisplayName: "Line-to-Line Voltage", Unit: "V",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 1000, HasMax: true,
		StaleAfterS: 300, Hot: true,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"reactive_power": {
		Key: "reactive_power", DisplayName: "Reactive Power", Unit: "VAR",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"apparent_power": {
		Key: "apparent_power", DisplayName: "Apparent Power", Unit: "VA",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"load_pct": {
		Key: "load_pct", DisplayName: "Load", Unit: "pct",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: true,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"phase_imbalance_pct": {
		Key: "phase_imbalance_pct", DisplayName: "Voltage Imbalance", Unit: "pct",
		ValueType: "gauge", Aggregation: "max",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"demand_peak_power": {
		Key: "demand_peak_power", DisplayName: "Peak Demand", Unit: "W",
		ValueType: "gauge", Aggregation: "max",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 900, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"battery_runtime": {
		Key: "battery_runtime", DisplayName: "Battery Runtime", Unit: "s",
		ValueType: "gauge", Aggregation: "min",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: true,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"battery_health_pct": {
		Key: "battery_health_pct", DisplayName: "Battery Health", Unit: "pct",
		ValueType: "gauge", Aggregation: "min",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 900, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"fuel_level_pct": {
		Key: "fuel_level_pct", DisplayName: "Fuel Level", Unit: "pct",
		ValueType: "gauge", Aggregation: "min",
		MinValid: 0, HasMin: true,
		MaxValid: 100, HasMax: true,
		StaleAfterS: 900, Hot: true,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"current_run_time": {
		Key: "current_run_time", DisplayName: "Current Run Time", Unit: "s",
		ValueType: "gauge", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"start_attempts": {
		Key: "start_attempts", DisplayName: "Start Attempts", Unit: "count",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 3600, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"transfer_count": {
		Key: "transfer_count", DisplayName: "Transfer Count", Unit: "count",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 3600, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"time_on_emergency": {
		Key: "time_on_emergency", DisplayName: "Time on Emergency", Unit: "s",
		ValueType: "counter", Aggregation: "last",
		MinValid: 0, HasMin: true,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 3600, Hot: false,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"operating_mode": {
		Key: "operating_mode", DisplayName: "Operating Mode", Unit: "text",
		ValueType: "text", Aggregation: "last",
		MinValid: 0, HasMin: false,
		MaxValid: 0, HasMax: false,
		StaleAfterS: 300, Hot: true,
		Group: "power", RateOf: "", RateScale: 1,
	},
	"component_temperature": {
		Key: "component_temperature", DisplayName: "Component Temperature", Unit: "C",
		ValueType: "gauge", Aggregation: "avg",
		MinValid: -20, HasMin: true,
		MaxValid: 150, HasMax: true,
		StaleAfterS: 300, Hot: false,
		Group: "thermal", RateOf: "", RateScale: 1,
	},
}

// MetricGroups maps a poll-profile group name to its metric keys.
var MetricGroups = map[string][]string{
	"compute":     {"cpu_utilization", "memory_utilization", "memory_used", "memory_total", "memory_available", "disk_utilization", "disk_used", "disk_total"},
	"cooling":     {"water_supply_temp", "water_return_temp", "water_setpoint_temp", "water_flow", "water_pressure", "water_diff_pressure", "valve_position_pct", "compressor_load_pct", "cooling_capacity", "cooling_output_pct", "thermal_load", "cop", "approach_temp", "supply_air_temp", "return_air_temp", "air_setpoint_temp", "filter_diff_pressure", "basin_level_pct", "makeup_water_flow", "vibration", "motor_temp", "vfd_frequency", "pump_speed_pct", "run_hours", "equipment_state", "alarm_state"},
	"environment": {"ambient_temperature", "relative_humidity", "dew_point", "airflow"},
	"interfaces":  {"if_admin_state", "if_oper_state", "if_speed", "if_in_octets", "if_out_octets", "if_in_bps", "if_out_bps", "if_in_errors", "if_out_errors", "if_in_discards", "if_out_discards", "if_in_error_rate"},
	"power":       {"power_draw", "psu_input_voltage", "psu_output_power", "psu_state", "energy_consumed", "voltage_ln", "current", "line_frequency", "power_factor", "voltage_thd_pct", "current_thd_pct", "harmonic_current_pct", "voltage_ll", "reactive_power", "apparent_power", "load_pct", "phase_imbalance_pct", "demand_peak_power", "battery_runtime", "battery_health_pct", "fuel_level_pct", "current_run_time", "start_attempts", "transfer_count", "time_on_emergency", "operating_mode"},
	"system":      {"sys_uptime", "reachable", "poll_latency"},
	"thermal":     {"cpu_temperature", "inlet_temperature", "exhaust_temperature", "fan_speed", "fan_speed_pct", "component_temperature"},
}
