#!/usr/bin/env python3
"""Generate Go, Python and TypeScript code from the contract definitions.

Deliberately depends on nothing but PyYAML: the contract must be regenerable on
a laptop with no protoc, no Go toolchain and no network. Run it with:

    python contracts/codegen.py            # write generated files
    python contracts/codegen.py --check    # exit 1 if anything is stale (CI)

Outputs
-------
    collector/pkg/models/messages_gen.go
    collector/pkg/models/metrics_gen.go
    backend/app/contracts/messages_gen.py
    backend/app/core/metrics_gen.py
    frontend/src/lib/metrics.gen.ts
    contracts/proto/dcim/telemetry/v1/telemetry.proto

Wire format
-----------
msgpack maps keyed by field NAME. Timestamps are int64 microseconds since the
Unix epoch, UTC, with 0 meaning unset - chosen over a language-native datetime
so that Go and Python cannot disagree about timezone handling. Unknown keys are
ignored on decode, which gives the forward compatibility protobuf tags would.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - operator-facing message
    sys.exit("PyYAML is required: pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"

BANNER = "// Code generated by contracts/codegen.py. DO NOT EDIT."
BANNER_PY = "# Code generated by contracts/codegen.py. DO NOT EDIT."

# Words that must keep their canonical casing when snake_case becomes CamelCase.
INITIALISMS = {
    "id": "ID", "ip": "IP", "cpu": "CPU", "url": "URL", "api": "API",
    "oid": "OID", "ms": "Ms", "bps": "Bps", "psu": "PSU", "pdu": "PDU",
    "ups": "UPS", "snmp": "SNMP", "gnmi": "GNMI", "http": "HTTP",
}


def camel(name: str) -> str:
    """snake_case -> CamelCase, honouring Go initialism conventions."""
    return "".join(INITIALISMS.get(p.lower(), p.capitalize()) for p in name.split("_"))


def align(rows: list[list[str]], indent: str = "	") -> list[str]:
    """Pad columns so the output is gofmt-clean without running gofmt.

    gofmt aligns runs of consecutive similar lines into columns. Reproducing
    that here keeps the generator toolchain-free (the whole point of writing it
    in Python) while still emitting code a Go reviewer would accept.
    """
    if not rows:
        return []
    width = max(len(r) for r in rows)
    padded = [r + [""] * (width - len(r)) for r in rows]
    widths = [max(len(r[c]) for r in padded) for c in range(width)]
    out = []
    for r in padded:
        cells = [r[c].ljust(widths[c]) for c in range(width - 1)]
        cells.append(r[-1])
        out.append((indent + " ".join(cells)).rstrip())
    return out


def align_struct(rows: list[list[str]]) -> list[str]:
    """Render struct fields as [name, type, tag, comment], gofmt-style.

    Name and type align across the whole struct, but the trailing-comment
    column aligns only across a RUN of consecutive commented lines - a field
    without a comment breaks the run. That is gofmt's actual rule, and
    reproducing it is what keeps generated code out of `gofmt -l`.
    """
    if not rows:
        return []
    w_name = max(len(r[0]) for r in rows)
    w_type = max(len(r[1]) for r in rows)

    out: list[str] = []
    i = 0
    while i < len(rows):
        if not rows[i][3]:
            r = rows[i]
            out.append(f"\t{r[0].ljust(w_name)} {r[1].ljust(w_type)} {r[2]}")
            i += 1
            continue
        run = []
        while i < len(rows) and rows[i][3]:
            run.append(rows[i])
            i += 1
        w_tag = max(len(r[2]) for r in run)
        for r in run:
            out.append(
                f"\t{r[0].ljust(w_name)} {r[1].ljust(w_type)} "
                f"{r[2].ljust(w_tag)} {r[3]}")
    return out


def load(path: Path) -> dict:
    with path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


# --------------------------------------------------------------------------
# type mapping
# --------------------------------------------------------------------------

GO_TYPES = {
    "string": "string", "double": "float64", "uint64": "uint64",
    "uint32": "uint32", "bool": "bool", "timestamp": "int64",
    "map<string,string>": "map[string]string",
}
PY_TYPES = {
    "string": "str", "double": "float", "uint64": "int", "uint32": "int",
    "bool": "bool", "timestamp": "int", "map<string,string>": "dict[str, str]",
}
PY_DEFAULTS = {
    "string": '""', "double": "0.0", "uint64": "0", "uint32": "0",
    "bool": "False", "timestamp": "0",
}
PROTO_TYPES = {
    "string": "string", "double": "double", "uint64": "uint64",
    "uint32": "uint32", "bool": "bool",
    "timestamp": "google.protobuf.Timestamp",
    "map<string,string>": "map<string, string>",
}


def go_type(t: str) -> str:
    if t.startswith("enum:"):
        return t.split(":", 1)[1]
    if t.startswith("repeated:"):
        return "[]" + t.split(":", 1)[1]
    return GO_TYPES[t]


def py_type(t: str) -> str:
    if t.startswith("enum:"):
        return "int"
    if t.startswith("repeated:"):
        return f'list["{t.split(":", 1)[1]}"]'
    return PY_TYPES[t]


def proto_type(t: str) -> str:
    if t.startswith("enum:"):
        return t.split(":", 1)[1]
    if t.startswith("repeated:"):
        return "repeated " + t.split(":", 1)[1]
    return PROTO_TYPES[t]


# --------------------------------------------------------------------------
# Go messages
# --------------------------------------------------------------------------

def gen_go_messages(schema: dict) -> str:
    out = [BANNER, "", "package models", "", "// Contract version "
           f"{schema['version']} ({schema['package']}).",
           "// Timestamps are int64 microseconds since the Unix epoch, UTC; 0 means unset.",
           ""]

    for ename, edef in schema["enums"].items():
        out.append(f"type {ename} int32")
        out.append("")
        out.append("const (")
        out += align([[f"{ename}{camel(v)}", ename, f"= {i}"]
                      for i, v in enumerate(edef["values"])])
        out.append(")")
        out.append("")
        out.append(f"var {ename.lower()}Names = map[{ename}]string{{")
        for i, v in enumerate(edef["values"]):
            out.append(f'\t{i}: "{v}",')
        out.append("}")
        out.append("")
        out.append(f"func (e {ename}) String() string {{")
        out.append(f'\tif s, ok := {ename.lower()}Names[e]; ok {{')
        out.append("\t\treturn s")
        out.append("\t}")
        out.append('\treturn "UNSPECIFIED"')
        out.append("}")
        out.append("")

    for mname, mdef in schema["messages"].items():
        if mdef.get("doc"):
            out.append(f"// {mname} - {mdef['doc']}")
        out.append(f"type {mname} struct {{")
        rows = []
        for f in mdef["fields"]:
            tag = f'`msgpack:"{f["name"]},omitempty" json:"{f["name"]},omitempty"`'
            comment = f"// {f['doc']}" if f.get("doc") else ""
            rows.append([camel(f["name"]), go_type(f["type"]), tag, comment])
        out += align_struct(rows)
        out.append("}")
        out.append("")

    st = schema["streams"]
    out.append("// Stream names and caps, from contracts/schema/messages_v1.yaml.")
    out.append("const (")
    out += align([[f"Stream{camel(key)}", f'= "{cfg["name"]}"']
                  for key, cfg in st.items()])
    out.append(")")
    out.append("")
    out.append("var StreamMaxLen = map[string]int64{")
    out += align([[f'"{cfg["name"]}":', f'{cfg["maxlen"]},']
                  for cfg in st.values()])
    out.append("}")
    out.append("")
    out.append(f"const SchemaVersion = {schema['version']}")
    out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------
# Python messages
# --------------------------------------------------------------------------

def gen_py_messages(schema: dict) -> str:
    out = [BANNER_PY, '"""Canonical telemetry contract, generated from '
           'contracts/schema/messages_v1.yaml.',
           "",
           "Timestamps are int microseconds since the Unix epoch, UTC; 0 means unset.",
           "Use ``ts_to_dt`` / ``dt_to_ts`` rather than converting by hand.",
           '"""',
           "from __future__ import annotations", "",
           "from dataclasses import dataclass, field, fields as dc_fields",
           "from datetime import datetime, timezone",
           "from enum import IntEnum",
           "from typing import Any", "", ""]

    out += [
        "def ts_to_dt(us: int) -> datetime | None:",
        '    """Contract microseconds -> aware UTC datetime (None when unset)."""',
        "    if not us:",
        "        return None",
        "    return datetime.fromtimestamp(us / 1_000_000, tz=timezone.utc)",
        "", "",
        "def dt_to_ts(dt: datetime | None) -> int:",
        '    """Aware datetime -> contract microseconds (0 when None)."""',
        "    if dt is None:",
        "        return 0",
        "    if dt.tzinfo is None:",
        "        dt = dt.replace(tzinfo=timezone.utc)",
        "    return int(dt.timestamp() * 1_000_000)",
        "", "",
    ]

    for ename, edef in schema["enums"].items():
        out.append(f"class {ename}(IntEnum):")
        for i, v in enumerate(edef["values"]):
            out.append(f"    {v} = {i}")
        out.append("")
        out.append("")

    out += [
        "class _Msg:",
        '    """Mixin: msgpack-map codec keyed by field name, tolerant of unknown keys."""',
        "",
        "    def to_dict(self) -> dict[str, Any]:",
        "        out: dict[str, Any] = {}",
        "        for f in dc_fields(self):",
        "            v = getattr(self, f.name)",
        "            if v in (None, 0, 0.0, '', False) or (isinstance(v, (dict, list)) and not v):",
        "                continue  # omitempty, matching the Go encoder",
        "            if isinstance(v, list):",
        "                out[f.name] = [i.to_dict() if hasattr(i, 'to_dict') else i for i in v]",
        "            elif hasattr(v, 'to_dict'):",
        "                out[f.name] = v.to_dict()",
        "            else:",
        "                out[f.name] = int(v) if isinstance(v, IntEnum) else v",
        "        return out",
        "",
        "    @classmethod",
        "    def from_dict(cls, d: dict[str, Any]):",
        "        kwargs: dict[str, Any] = {}",
        "        nested = getattr(cls, '_nested', {})",
        "        for f in dc_fields(cls):",
        "            if f.name not in d:",
        "                continue  # absent == default; forward compatible",
        "            v = d[f.name]",
        "            sub = nested.get(f.name)",
        "            if sub is not None and isinstance(v, list):",
        "                v = [sub.from_dict(i) if isinstance(i, dict) else i for i in v]",
        "            kwargs[f.name] = v",
        "        return cls(**kwargs)",
        "", "",
    ]

    for mname, mdef in schema["messages"].items():
        out.append("@dataclass(slots=True)")
        out.append(f"class {mname}(_Msg):")
        if mdef.get("doc"):
            out.append(f'    """{mdef["doc"]}"""')
        nested = {}
        for f in mdef["fields"]:
            t = f["type"]
            pt = py_type(t)
            if t.startswith("repeated:"):
                nested[f["name"]] = t.split(":", 1)[1]
                out.append(f"    {f['name']}: {pt} = field(default_factory=list)")
            elif t == "map<string,string>":
                out.append(f"    {f['name']}: {pt} = field(default_factory=dict)")
            else:
                out.append(f"    {f['name']}: {pt} = {PY_DEFAULTS[t] if not t.startswith('enum:') else '0'}")
        if nested:
            out.append("")
            out.append("    _nested = {" + ", ".join(
                f'"{k}": {v}' for k, v in nested.items()) + "}")
        out.append("")
        out.append("")

    st = schema["streams"]
    out.append("class Stream:")
    out.append('    """Redis stream names and caps."""')
    out.append("")
    for key, s in st.items():
        out.append(f'    {key.upper()} = "{s["name"]}"')
    out.append("")
    out.append("")
    out.append("STREAM_MAXLEN = {")
    for s in st.values():
        out.append(f'    "{s["name"]}": {s["maxlen"]},')
    out.append("}")
    out.append("")
    out.append(f"SCHEMA_VERSION = {schema['version']}")
    out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------
# protobuf IDL (emitted for the future transport; nothing consumes it yet)
# --------------------------------------------------------------------------

def gen_proto(schema: dict) -> str:
    out = ["// Code generated by contracts/codegen.py. DO NOT EDIT.",
           "//",
           "// Emitted for the eventual protobuf transport. The wire format today is",
           "// msgpack keyed by field name - see docs/05-telemetry-contract.md.",
           'syntax = "proto3";', "",
           f"package {schema['package']};", "",
           'import "google/protobuf/timestamp.proto";', ""]

    for ename, edef in schema["enums"].items():
        out.append(f"enum {ename} {{")
        prefix = "".join("_" + c if c.isupper() else c.upper()
                         for c in ename).lstrip("_")
        for i, v in enumerate(edef["values"]):
            out.append(f"  {prefix}_{v} = {i};")
        out.append("}")
        out.append("")

    for mname, mdef in schema["messages"].items():
        if mdef.get("doc"):
            out.append(f"// {mdef['doc']}")
        out.append(f"message {mname} {{")
        for f in mdef["fields"]:
            doc = f"  // {f['doc']}" if f.get("doc") else ""
            out.append(f"  {proto_type(f['type'])} {f['name']} = {f['tag']};{doc}")
        out.append("}")
        out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------
# metric registry
# --------------------------------------------------------------------------

def gen_go_metrics(reg: dict) -> str:
    out = [BANNER, "", "package models", "",
           "// Canonical metric registry, generated from contracts/metrics/registry.yaml.",
           "// A metric key absent from MetricDefs is a hard validation failure at emit time.",
           "", "type MetricDef struct {"]
    out += align([
        ["Key", "string"], ["DisplayName", "string"], ["Unit", "string"],
        ["ValueType", "string"], ["Aggregation", "string"],
        ["MinValid", "float64"], ["MaxValid", "float64"],
        ["HasMin", "bool"], ["HasMax", "bool"], ["StaleAfterS", "int"],
        ["Hot", "bool"], ["Group", "string"], ["RateOf", "string"],
        ["RateScale", "float64"],
    ])
    out += ["}", "", "const ("]
    out += align([[f'Metric{camel(m["key"])}', f'= "{m["key"]}"']
                  for m in reg["metrics"]])
    out.append(")")
    out.append("")
    out.append("var MetricDefs = map[string]MetricDef{")
    for m in reg["metrics"]:
        has_min = "min_valid" in m
        has_max = "max_valid" in m
        out.append(f'\t"{m["key"]}": {{')
        out.append(f'\t\tKey: "{m["key"]}", DisplayName: "{m["display_name"]}", Unit: "{m["unit"]}",')
        out.append(f'\t\tValueType: "{m["value_type"]}", Aggregation: "{m.get("aggregation", "avg")}",')
        out.append(f'\t\tMinValid: {float(m.get("min_valid", 0)):g}, HasMin: {str(has_min).lower()},')
        out.append(f'\t\tMaxValid: {float(m.get("max_valid", 0)):g}, HasMax: {str(has_max).lower()},')
        out.append(f'\t\tStaleAfterS: {m.get("stale_after_s", 300)}, Hot: {str(bool(m.get("hot"))).lower()},')
        out.append(f'\t\tGroup: "{m.get("group", "")}", RateOf: "{m.get("rate_of", "")}", '
                   f'RateScale: {float(m.get("rate_scale", 1)):g},')
        out.append("\t},")
    out.append("}")
    out.append("")
    out.append("// MetricGroups maps a poll-profile group name to its metric keys.")
    groups: dict[str, list[str]] = {}
    for m in reg["metrics"]:
        groups.setdefault(m.get("group", "other"), []).append(m["key"])
    out.append("var MetricGroups = map[string][]string{")
    out += align([[f'"{g}":', "{" + ", ".join(f'"{k}"' for k in keys) + "},"]
                  for g, keys in sorted(groups.items())])
    out.append("}")
    out.append("")
    return "\n".join(out)


def gen_py_metrics(reg: dict) -> str:
    out = [BANNER_PY,
           '"""Canonical metric registry, generated from contracts/metrics/registry.yaml."""',
           "from __future__ import annotations", "",
           "from dataclasses import dataclass", "", "",
           "@dataclass(frozen=True, slots=True)",
           "class MetricDef:",
           "    key: str",
           "    display_name: str",
           "    unit: str",
           "    value_type: str",
           "    aggregation: str",
           "    min_valid: float | None",
           "    max_valid: float | None",
           "    stale_after_s: int",
           "    hot: bool",
           "    group: str",
           "    rate_of: str | None",
           "    rate_scale: float",
           "    device_types: tuple[str, ...]",
           "", "", "METRICS: dict[str, MetricDef] = {"]
    for m in reg["metrics"]:
        dts = ", ".join(f'"{d}"' for d in m.get("device_types", []))
        dts = f"({dts},)" if dts else "()"
        out.append(f'    "{m["key"]}": MetricDef(')
        out.append(f'        key="{m["key"]}", display_name="{m["display_name"]}", unit="{m["unit"]}",')
        out.append(f'        value_type="{m["value_type"]}", aggregation="{m.get("aggregation", "avg")}",')
        out.append(f'        min_valid={m.get("min_valid", None)!r}, max_valid={m.get("max_valid", None)!r},')
        out.append(f'        stale_after_s={m.get("stale_after_s", 300)}, hot={bool(m.get("hot"))!r},')
        out.append(f'        group="{m.get("group", "")}", rate_of={m.get("rate_of", None)!r}, '
                   f'rate_scale={float(m.get("rate_scale", 1))!r},')
        out.append(f'        device_types={dts},')
        out.append("    ),")
    out.append("}")
    out.append("")
    out.append("HOT_METRICS = tuple(k for k, m in METRICS.items() if m.hot)")
    out.append("COUNTER_METRICS = tuple(k for k, m in METRICS.items() if m.value_type == 'counter')")
    out.append("# counter key -> the gauge key its rate is written to")
    out.append("RATE_TARGETS = {m.rate_of: k for k, m in METRICS.items() if m.rate_of}")
    out.append("")
    return "\n".join(out)


def mapping_groups() -> dict[str, list[str]]:
    """Named profile blocks a poll profile's `metric_groups` can select.

    SNMP only, and that is not an omission. `MetricGroups` is read in exactly
    one place in the collector - adapters/snmp/snmp.go - so a group named on a
    profile used by any other protocol selects nothing. gNMI subscribes from
    its own mapping file, BACnet reads its object map, Modbus its register
    templates; none of them consults the profile.

    Which makes the seeded `gnmi-stream` profile's {interfaces} group
    decorative: it reads like configuration and changes nothing. Generating
    this list is what lets the API say so instead of accepting a group that
    will never be looked up.
    """
    doc = load(CONTRACTS / "mappings" / "snmp" / "standard.yaml")
    return {"snmp": [p["name"] for p in doc.get("profiles", [])]}


def gen_py_mapping_groups(groups: dict[str, list[str]]) -> str:
    out = [BANNER_PY,
           '"""Mapping profile groups, generated from contracts/mappings/*."""',
           "from __future__ import annotations", "", "",
           "#: protocol -> the group names a poll profile may select.",
           "#:",
           "#: SNMP is the only entry because MetricGroups is read in exactly",
           "#: one place in the collector, the SNMP adapter. gNMI subscribes",
           "#: from its own mapping file, BACnet reads its object map and",
           "#: Modbus its register templates - a group named on a profile used",
           "#: by any of those selects nothing at all.",
           "MAPPING_GROUPS: dict[str, tuple[str, ...]] = {"]
    for protocol, names in sorted(groups.items()):
        joined = ", ".join(f'"{n}"' for n in names)
        out.append(f'    "{protocol}": ({joined},),' if names
                   else f'    "{protocol}": (),')
    out.append("}")
    out.append("")
    out.append("#: Every group name known to any protocol.")
    out.append("ALL_GROUPS = frozenset(g for gs in MAPPING_GROUPS.values() "
               "for g in gs)")
    out.append("")
    return "\n".join(out)


def gen_ts_metrics(reg: dict) -> str:
    keys = [m["key"] for m in reg["metrics"]]
    out = ["// Code generated by contracts/codegen.py. DO NOT EDIT.",
           "",
           "export type MetricKey =",
           *[f"  | '{k}'" for k in keys],
           "  ;",
           "",
           "export interface MetricDef {",
           "  key: MetricKey;",
           "  displayName: string;",
           "  unit: string;",
           "  valueType: 'gauge' | 'counter' | 'delta' | 'bool' | 'text';",
           "  aggregation: string;",
           "  minValid: number | null;",
           "  maxValid: number | null;",
           "  staleAfterS: number;",
           "  hot: boolean;",
           "  group: string;",
           "}",
           "",
           "export const METRICS: Record<MetricKey, MetricDef> = {"]
    for m in reg["metrics"]:
        out.append(f"  '{m['key']}': {{")
        out.append(f"    key: '{m['key']}', displayName: {m['display_name']!r}.replace(/^'|'$/g, ''),")
        out.append(f"    unit: '{m['unit']}', valueType: '{m['value_type']}',")
        out.append(f"    aggregation: '{m.get('aggregation', 'avg')}',")
        out.append(f"    minValid: {m.get('min_valid', 'null') if 'min_valid' in m else 'null'},")
        out.append(f"    maxValid: {m.get('max_valid', 'null') if 'max_valid' in m else 'null'},")
        out.append(f"    staleAfterS: {m.get('stale_after_s', 300)}, hot: {str(bool(m.get('hot'))).lower()},")
        out.append(f"    group: '{m.get('group', '')}',")
        out.append("  },")
    out.append("};")
    out.append("")
    out.append("export const HOT_METRICS = (Object.keys(METRICS) as MetricKey[])")
    out.append("  .filter((k) => METRICS[k].hot);")
    out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------

def emit(path: Path, content: str, check: bool, stale: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return
    if check:
        stale.append(str(path.relative_to(ROOT)))
        return
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(ROOT)}")


def validate(reg: dict) -> None:
    """Fail loudly on registry mistakes that would otherwise surface at runtime."""
    seen: set[str] = set()
    keys = {m["key"] for m in reg["metrics"]}
    for m in reg["metrics"]:
        k = m["key"]
        if k in seen:
            sys.exit(f"duplicate metric key: {k}")
        seen.add(k)
        if k != k.lower() or " " in k:
            sys.exit(f"metric key must be lower snake_case: {k}")
        if m["value_type"] not in ("gauge", "counter", "delta", "bool", "text"):
            sys.exit(f"{k}: bad value_type {m['value_type']}")
        if "min_valid" in m and "max_valid" in m and m["min_valid"] > m["max_valid"]:
            sys.exit(f"{k}: min_valid > max_valid")
        ro = m.get("rate_of")
        if ro:
            if ro not in keys:
                sys.exit(f"{k}: rate_of references unknown metric {ro}")
            if m["value_type"] != "gauge":
                sys.exit(f"{k}: a rate_of metric must be a gauge")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="do not write; exit 1 if any output is stale")
    args = ap.parse_args()

    schema = load(CONTRACTS / "schema" / "messages_v1.yaml")
    reg = load(CONTRACTS / "metrics" / "registry.yaml")
    validate(reg)

    stale: list[str] = []
    emit(ROOT / "collector/pkg/models/messages_gen.go", gen_go_messages(schema), args.check, stale)
    emit(ROOT / "collector/pkg/models/metrics_gen.go", gen_go_metrics(reg), args.check, stale)
    emit(ROOT / "backend/app/contracts/messages_gen.py", gen_py_messages(schema), args.check, stale)
    emit(ROOT / "backend/app/core/metrics_gen.py", gen_py_metrics(reg), args.check, stale)
    emit(ROOT / "backend/app/core/mappings_gen.py",
         gen_py_mapping_groups(mapping_groups()), args.check, stale)
    emit(ROOT / "frontend/src/lib/metrics.gen.ts", gen_ts_metrics(reg), args.check, stale)
    emit(CONTRACTS / "proto/dcim/telemetry/v1/telemetry.proto", gen_proto(schema), args.check, stale)

    if stale:
        print("generated code is stale; run `python contracts/codegen.py`:", file=sys.stderr)
        for s in stale:
            print(f"  {s}", file=sys.stderr)
        return 1
    if args.check:
        print("generated code is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
