// Code generated by contracts/codegen.py. DO NOT EDIT.

export type MetricKey =
  | 'sys_uptime'
  | 'reachable'
  | 'poll_latency'
  | 'cpu_utilization'
  | 'cpu_temperature'
  | 'memory_utilization'
  | 'memory_used'
  | 'memory_total'
  | 'memory_available'
  | 'disk_utilization'
  | 'disk_used'
  | 'disk_total'
  | 'inlet_temperature'
  | 'exhaust_temperature'
  | 'power_draw'
  | 'fan_speed'
  | 'fan_speed_pct'
  | 'psu_input_voltage'
  | 'psu_output_power'
  | 'psu_state'
  | 'energy_consumed'
  | 'if_admin_state'
  | 'if_oper_state'
  | 'if_speed'
  | 'if_in_octets'
  | 'if_out_octets'
  | 'if_in_bps'
  | 'if_out_bps'
  | 'if_in_errors'
  | 'if_out_errors'
  | 'if_in_discards'
  | 'if_out_discards'
  | 'if_in_error_rate'
  | 'ambient_temperature'
  | 'relative_humidity'
  | 'dew_point'
  | 'airflow'
  | 'water_supply_temp'
  | 'water_return_temp'
  | 'water_setpoint_temp'
  | 'water_flow'
  | 'water_pressure'
  | 'water_diff_pressure'
  | 'valve_position_pct'
  | 'compressor_load_pct'
  | 'cooling_capacity'
  | 'cooling_output_pct'
  | 'thermal_load'
  | 'cop'
  | 'approach_temp'
  | 'supply_air_temp'
  | 'return_air_temp'
  | 'air_setpoint_temp'
  | 'filter_diff_pressure'
  | 'basin_level_pct'
  | 'makeup_water_flow'
  | 'vibration'
  | 'motor_temp'
  | 'vfd_frequency'
  | 'pump_speed_pct'
  | 'run_hours'
  | 'equipment_state'
  | 'alarm_state'
  | 'voltage_ln'
  | 'current'
  | 'line_frequency'
  | 'power_factor'
  | 'voltage_thd_pct'
  | 'current_thd_pct'
  | 'harmonic_current_pct'
  | 'voltage_ll'
  | 'reactive_power'
  | 'apparent_power'
  | 'load_pct'
  | 'phase_imbalance_pct'
  | 'demand_peak_power'
  | 'battery_runtime'
  | 'battery_health_pct'
  | 'fuel_level_pct'
  | 'current_run_time'
  | 'start_attempts'
  | 'transfer_count'
  | 'time_on_emergency'
  | 'operating_mode'
  ;

export interface MetricDef {
  key: MetricKey;
  displayName: string;
  unit: string;
  valueType: 'gauge' | 'counter' | 'delta' | 'bool' | 'text';
  aggregation: string;
  minValid: number | null;
  maxValid: number | null;
  staleAfterS: number;
  hot: boolean;
  group: string;
}

export const METRICS: Record<MetricKey, MetricDef> = {
  'sys_uptime': {
    key: 'sys_uptime', displayName: 'System Uptime'.replace(/^'|'$/g, ''),
    unit: 's', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'system',
  },
  'reachable': {
    key: 'reachable', displayName: 'Reachable'.replace(/^'|'$/g, ''),
    unit: 'bool', valueType: 'bool',
    aggregation: 'last',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: true,
    group: 'system',
  },
  'poll_latency': {
    key: 'poll_latency', displayName: 'Poll Latency'.replace(/^'|'$/g, ''),
    unit: 'ms', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 60000,
    staleAfterS: 300, hot: false,
    group: 'system',
  },
  'cpu_utilization': {
    key: 'cpu_utilization', displayName: 'CPU Utilization'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 120, hot: true,
    group: 'compute',
  },
  'cpu_temperature': {
    key: 'cpu_temperature', displayName: 'CPU Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'max',
    minValid: -20,
    maxValid: 130,
    staleAfterS: 120, hot: true,
    group: 'thermal',
  },
  'memory_utilization': {
    key: 'memory_utilization', displayName: 'Memory Utilization'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 120, hot: true,
    group: 'compute',
  },
  'memory_used': {
    key: 'memory_used', displayName: 'Memory Used'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 120, hot: false,
    group: 'compute',
  },
  'memory_total': {
    key: 'memory_total', displayName: 'Memory Total'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'gauge',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 3600, hot: false,
    group: 'compute',
  },
  'memory_available': {
    key: 'memory_available', displayName: 'Memory Available'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 120, hot: false,
    group: 'compute',
  },
  'disk_utilization': {
    key: 'disk_utilization', displayName: 'Disk Utilization'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'max',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 300, hot: false,
    group: 'compute',
  },
  'disk_used': {
    key: 'disk_used', displayName: 'Disk Used'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'compute',
  },
  'disk_total': {
    key: 'disk_total', displayName: 'Disk Total'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'gauge',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 3600, hot: false,
    group: 'compute',
  },
  'inlet_temperature': {
    key: 'inlet_temperature', displayName: 'Inlet Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'max',
    minValid: -20,
    maxValid: 80,
    staleAfterS: 120, hot: true,
    group: 'thermal',
  },
  'exhaust_temperature': {
    key: 'exhaust_temperature', displayName: 'Exhaust Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'max',
    minValid: -20,
    maxValid: 100,
    staleAfterS: 120, hot: false,
    group: 'thermal',
  },
  'power_draw': {
    key: 'power_draw', displayName: 'Power Draw'.replace(/^'|'$/g, ''),
    unit: 'W', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 20000000,
    staleAfterS: 120, hot: true,
    group: 'power',
  },
  'fan_speed': {
    key: 'fan_speed', displayName: 'Fan Speed'.replace(/^'|'$/g, ''),
    unit: 'rpm', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 30000,
    staleAfterS: 120, hot: false,
    group: 'thermal',
  },
  'fan_speed_pct': {
    key: 'fan_speed_pct', displayName: 'Fan Speed Percent'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 120, hot: false,
    group: 'thermal',
  },
  'psu_input_voltage': {
    key: 'psu_input_voltage', displayName: 'PSU Input Voltage'.replace(/^'|'$/g, ''),
    unit: 'V', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 600,
    staleAfterS: 120, hot: false,
    group: 'power',
  },
  'psu_output_power': {
    key: 'psu_output_power', displayName: 'PSU Output Power'.replace(/^'|'$/g, ''),
    unit: 'W', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 5000,
    staleAfterS: 120, hot: false,
    group: 'power',
  },
  'psu_state': {
    key: 'psu_state', displayName: 'PSU State'.replace(/^'|'$/g, ''),
    unit: 'bool', valueType: 'bool',
    aggregation: 'last',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'power',
  },
  'energy_consumed': {
    key: 'energy_consumed', displayName: 'Energy Consumed'.replace(/^'|'$/g, ''),
    unit: 'kWh', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 600, hot: false,
    group: 'power',
  },
  'if_admin_state': {
    key: 'if_admin_state', displayName: 'Interface Admin State'.replace(/^'|'$/g, ''),
    unit: 'bool', valueType: 'bool',
    aggregation: 'last',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_oper_state': {
    key: 'if_oper_state', displayName: 'Interface Oper State'.replace(/^'|'$/g, ''),
    unit: 'bool', valueType: 'bool',
    aggregation: 'last',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_speed': {
    key: 'if_speed', displayName: 'Interface Speed'.replace(/^'|'$/g, ''),
    unit: 'bps', valueType: 'gauge',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 3600, hot: false,
    group: 'interfaces',
  },
  'if_in_octets': {
    key: 'if_in_octets', displayName: 'Interface In Octets'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_out_octets': {
    key: 'if_out_octets', displayName: 'Interface Out Octets'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_in_bps': {
    key: 'if_in_bps', displayName: 'Interface In Throughput'.replace(/^'|'$/g, ''),
    unit: 'bps', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_out_bps': {
    key: 'if_out_bps', displayName: 'Interface Out Throughput'.replace(/^'|'$/g, ''),
    unit: 'bps', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_in_errors': {
    key: 'if_in_errors', displayName: 'Interface In Errors'.replace(/^'|'$/g, ''),
    unit: 'count', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_out_errors': {
    key: 'if_out_errors', displayName: 'Interface Out Errors'.replace(/^'|'$/g, ''),
    unit: 'count', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_in_discards': {
    key: 'if_in_discards', displayName: 'Interface In Discards'.replace(/^'|'$/g, ''),
    unit: 'count', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_out_discards': {
    key: 'if_out_discards', displayName: 'Interface Out Discards'.replace(/^'|'$/g, ''),
    unit: 'count', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_in_error_rate': {
    key: 'if_in_error_rate', displayName: 'Interface In Error Rate'.replace(/^'|'$/g, ''),
    unit: 'count_per_s', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'ambient_temperature': {
    key: 'ambient_temperature', displayName: 'Ambient Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'max',
    minValid: -40,
    maxValid: 90,
    staleAfterS: 120, hot: true,
    group: 'environment',
  },
  'relative_humidity': {
    key: 'relative_humidity', displayName: 'Relative Humidity'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 120, hot: true,
    group: 'environment',
  },
  'dew_point': {
    key: 'dew_point', displayName: 'Dew Point'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'avg',
    minValid: -40,
    maxValid: 60,
    staleAfterS: 120, hot: false,
    group: 'environment',
  },
  'airflow': {
    key: 'airflow', displayName: 'Airflow'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 120, hot: false,
    group: 'environment',
  },
  'water_supply_temp': {
    key: 'water_supply_temp', displayName: 'Water Supply Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'avg',
    minValid: -20,
    maxValid: 120,
    staleAfterS: 300, hot: true,
    group: 'cooling',
  },
  'water_return_temp': {
    key: 'water_return_temp', displayName: 'Water Return Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'avg',
    minValid: -20,
    maxValid: 120,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'water_setpoint_temp': {
    key: 'water_setpoint_temp', displayName: 'Water Setpoint'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'last',
    minValid: -20,
    maxValid: 120,
    staleAfterS: 900, hot: false,
    group: 'cooling',
  },
  'water_flow': {
    key: 'water_flow', displayName: 'Water Flow'.replace(/^'|'$/g, ''),
    unit: 'L/s', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'water_pressure': {
    key: 'water_pressure', displayName: 'Water Pressure'.replace(/^'|'$/g, ''),
    unit: 'kPa', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'water_diff_pressure': {
    key: 'water_diff_pressure', displayName: 'Differential Pressure'.replace(/^'|'$/g, ''),
    unit: 'kPa', valueType: 'gauge',
    aggregation: 'avg',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'valve_position_pct': {
    key: 'valve_position_pct', displayName: 'Valve Position'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'compressor_load_pct': {
    key: 'compressor_load_pct', displayName: 'Compressor Load'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 300, hot: true,
    group: 'cooling',
  },
  'cooling_capacity': {
    key: 'cooling_capacity', displayName: 'Cooling Capacity'.replace(/^'|'$/g, ''),
    unit: 'W', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'cooling_output_pct': {
    key: 'cooling_output_pct', displayName: 'Cooling Output'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'thermal_load': {
    key: 'thermal_load', displayName: 'Thermal Load'.replace(/^'|'$/g, ''),
    unit: 'W', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'cop': {
    key: 'cop', displayName: 'Coefficient of Performance'.replace(/^'|'$/g, ''),
    unit: 'ratio', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 20,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'approach_temp': {
    key: 'approach_temp', displayName: 'Approach Temperature'.replace(/^'|'$/g, ''),
    unit: 'K', valueType: 'gauge',
    aggregation: 'avg',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'supply_air_temp': {
    key: 'supply_air_temp', displayName: 'Supply Air Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'avg',
    minValid: -20,
    maxValid: 80,
    staleAfterS: 300, hot: true,
    group: 'cooling',
  },
  'return_air_temp': {
    key: 'return_air_temp', displayName: 'Return Air Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'avg',
    minValid: -20,
    maxValid: 80,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'air_setpoint_temp': {
    key: 'air_setpoint_temp', displayName: 'Air Setpoint'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'last',
    minValid: -20,
    maxValid: 80,
    staleAfterS: 900, hot: false,
    group: 'cooling',
  },
  'filter_diff_pressure': {
    key: 'filter_diff_pressure', displayName: 'Filter Differential Pressure'.replace(/^'|'$/g, ''),
    unit: 'kPa', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 600, hot: false,
    group: 'cooling',
  },
  'basin_level_pct': {
    key: 'basin_level_pct', displayName: 'Basin Level'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 600, hot: false,
    group: 'cooling',
  },
  'makeup_water_flow': {
    key: 'makeup_water_flow', displayName: 'Makeup Water Flow'.replace(/^'|'$/g, ''),
    unit: 'L/s', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 600, hot: false,
    group: 'cooling',
  },
  'vibration': {
    key: 'vibration', displayName: 'Vibration'.replace(/^'|'$/g, ''),
    unit: 'mm/s', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 600, hot: false,
    group: 'cooling',
  },
  'motor_temp': {
    key: 'motor_temp', displayName: 'Motor Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'avg',
    minValid: -20,
    maxValid: 200,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'vfd_frequency': {
    key: 'vfd_frequency', displayName: 'VFD Output Frequency'.replace(/^'|'$/g, ''),
    unit: 'Hz', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 200,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'pump_speed_pct': {
    key: 'pump_speed_pct', displayName: 'Pump Speed'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 300, hot: false,
    group: 'cooling',
  },
  'run_hours': {
    key: 'run_hours', displayName: 'Run Hours'.replace(/^'|'$/g, ''),
    unit: 'h', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 3600, hot: false,
    group: 'cooling',
  },
  'equipment_state': {
    key: 'equipment_state', displayName: 'Equipment State'.replace(/^'|'$/g, ''),
    unit: 'bool', valueType: 'bool',
    aggregation: 'last',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: true,
    group: 'cooling',
  },
  'alarm_state': {
    key: 'alarm_state', displayName: 'Alarm State'.replace(/^'|'$/g, ''),
    unit: 'bool', valueType: 'bool',
    aggregation: 'max',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: true,
    group: 'cooling',
  },
  'voltage_ln': {
    key: 'voltage_ln', displayName: 'Line-to-Neutral Voltage'.replace(/^'|'$/g, ''),
    unit: 'V', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 600,
    staleAfterS: 300, hot: false,
    group: 'power',
  },
  'current': {
    key: 'current', displayName: 'Current'.replace(/^'|'$/g, ''),
    unit: 'A', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: true,
    group: 'power',
  },
  'line_frequency': {
    key: 'line_frequency', displayName: 'Line Frequency'.replace(/^'|'$/g, ''),
    unit: 'Hz', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 300, hot: false,
    group: 'power',
  },
  'power_factor': {
    key: 'power_factor', displayName: 'Power Factor'.replace(/^'|'$/g, ''),
    unit: 'ratio', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 1,
    staleAfterS: 300, hot: false,
    group: 'power',
  },
  'voltage_thd_pct': {
    key: 'voltage_thd_pct', displayName: 'Voltage THD'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 600, hot: false,
    group: 'power',
  },
  'current_thd_pct': {
    key: 'current_thd_pct', displayName: 'Current THD'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 600, hot: false,
    group: 'power',
  },
  'harmonic_current_pct': {
    key: 'harmonic_current_pct', displayName: 'Harmonic Current'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 600, hot: false,
    group: 'power',
  },
  'voltage_ll': {
    key: 'voltage_ll', displayName: 'Line-to-Line Voltage'.replace(/^'|'$/g, ''),
    unit: 'V', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 1000,
    staleAfterS: 300, hot: true,
    group: 'power',
  },
  'reactive_power': {
    key: 'reactive_power', displayName: 'Reactive Power'.replace(/^'|'$/g, ''),
    unit: 'VAR', valueType: 'gauge',
    aggregation: 'avg',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'power',
  },
  'apparent_power': {
    key: 'apparent_power', displayName: 'Apparent Power'.replace(/^'|'$/g, ''),
    unit: 'VA', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'power',
  },
  'load_pct': {
    key: 'load_pct', displayName: 'Load'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: true,
    group: 'power',
  },
  'phase_imbalance_pct': {
    key: 'phase_imbalance_pct', displayName: 'Voltage Imbalance'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'max',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'power',
  },
  'demand_peak_power': {
    key: 'demand_peak_power', displayName: 'Peak Demand'.replace(/^'|'$/g, ''),
    unit: 'W', valueType: 'gauge',
    aggregation: 'max',
    minValid: 0,
    maxValid: null,
    staleAfterS: 900, hot: false,
    group: 'power',
  },
  'battery_runtime': {
    key: 'battery_runtime', displayName: 'Battery Runtime'.replace(/^'|'$/g, ''),
    unit: 's', valueType: 'gauge',
    aggregation: 'min',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: true,
    group: 'power',
  },
  'battery_health_pct': {
    key: 'battery_health_pct', displayName: 'Battery Health'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'min',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 900, hot: false,
    group: 'power',
  },
  'fuel_level_pct': {
    key: 'fuel_level_pct', displayName: 'Fuel Level'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'min',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 900, hot: true,
    group: 'power',
  },
  'current_run_time': {
    key: 'current_run_time', displayName: 'Current Run Time'.replace(/^'|'$/g, ''),
    unit: 's', valueType: 'gauge',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'power',
  },
  'start_attempts': {
    key: 'start_attempts', displayName: 'Start Attempts'.replace(/^'|'$/g, ''),
    unit: 'count', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 3600, hot: false,
    group: 'power',
  },
  'transfer_count': {
    key: 'transfer_count', displayName: 'Transfer Count'.replace(/^'|'$/g, ''),
    unit: 'count', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 3600, hot: false,
    group: 'power',
  },
  'time_on_emergency': {
    key: 'time_on_emergency', displayName: 'Time on Emergency'.replace(/^'|'$/g, ''),
    unit: 's', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 3600, hot: false,
    group: 'power',
  },
  'operating_mode': {
    key: 'operating_mode', displayName: 'Operating Mode'.replace(/^'|'$/g, ''),
    unit: 'text', valueType: 'text',
    aggregation: 'last',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: true,
    group: 'power',
  },
};

export const HOT_METRICS = (Object.keys(METRICS) as MetricKey[])
  .filter((k) => METRICS[k].hot);
