// Code generated by contracts/codegen.py. DO NOT EDIT.

export type MetricKey =
  | 'sys_uptime'
  | 'reachable'
  | 'poll_latency'
  | 'cpu_utilization'
  | 'cpu_temperature'
  | 'memory_utilization'
  | 'memory_used'
  | 'memory_total'
  | 'memory_available'
  | 'disk_utilization'
  | 'disk_used'
  | 'disk_total'
  | 'inlet_temperature'
  | 'exhaust_temperature'
  | 'power_draw'
  | 'fan_speed'
  | 'fan_speed_pct'
  | 'psu_input_voltage'
  | 'psu_output_power'
  | 'psu_state'
  | 'energy_consumed'
  | 'if_admin_state'
  | 'if_oper_state'
  | 'if_speed'
  | 'if_in_octets'
  | 'if_out_octets'
  | 'if_in_bps'
  | 'if_out_bps'
  | 'if_in_errors'
  | 'if_out_errors'
  | 'if_in_discards'
  | 'if_out_discards'
  | 'if_in_error_rate'
  | 'ambient_temperature'
  | 'relative_humidity'
  | 'dew_point'
  | 'airflow'
  ;

export interface MetricDef {
  key: MetricKey;
  displayName: string;
  unit: string;
  valueType: 'gauge' | 'counter' | 'delta' | 'bool' | 'text';
  aggregation: string;
  minValid: number | null;
  maxValid: number | null;
  staleAfterS: number;
  hot: boolean;
  group: string;
}

export const METRICS: Record<MetricKey, MetricDef> = {
  'sys_uptime': {
    key: 'sys_uptime', displayName: 'System Uptime'.replace(/^'|'$/g, ''),
    unit: 's', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'system',
  },
  'reachable': {
    key: 'reachable', displayName: 'Reachable'.replace(/^'|'$/g, ''),
    unit: 'bool', valueType: 'bool',
    aggregation: 'last',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: true,
    group: 'system',
  },
  'poll_latency': {
    key: 'poll_latency', displayName: 'Poll Latency'.replace(/^'|'$/g, ''),
    unit: 'ms', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 60000,
    staleAfterS: 300, hot: false,
    group: 'system',
  },
  'cpu_utilization': {
    key: 'cpu_utilization', displayName: 'CPU Utilization'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 120, hot: true,
    group: 'compute',
  },
  'cpu_temperature': {
    key: 'cpu_temperature', displayName: 'CPU Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'max',
    minValid: -20,
    maxValid: 130,
    staleAfterS: 120, hot: true,
    group: 'thermal',
  },
  'memory_utilization': {
    key: 'memory_utilization', displayName: 'Memory Utilization'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 120, hot: true,
    group: 'compute',
  },
  'memory_used': {
    key: 'memory_used', displayName: 'Memory Used'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 120, hot: false,
    group: 'compute',
  },
  'memory_total': {
    key: 'memory_total', displayName: 'Memory Total'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'gauge',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 3600, hot: false,
    group: 'compute',
  },
  'memory_available': {
    key: 'memory_available', displayName: 'Memory Available'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 120, hot: false,
    group: 'compute',
  },
  'disk_utilization': {
    key: 'disk_utilization', displayName: 'Disk Utilization'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'max',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 300, hot: false,
    group: 'compute',
  },
  'disk_used': {
    key: 'disk_used', displayName: 'Disk Used'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'compute',
  },
  'disk_total': {
    key: 'disk_total', displayName: 'Disk Total'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'gauge',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 3600, hot: false,
    group: 'compute',
  },
  'inlet_temperature': {
    key: 'inlet_temperature', displayName: 'Inlet Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'max',
    minValid: -20,
    maxValid: 80,
    staleAfterS: 120, hot: true,
    group: 'thermal',
  },
  'exhaust_temperature': {
    key: 'exhaust_temperature', displayName: 'Exhaust Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'max',
    minValid: -20,
    maxValid: 100,
    staleAfterS: 120, hot: false,
    group: 'thermal',
  },
  'power_draw': {
    key: 'power_draw', displayName: 'Power Draw'.replace(/^'|'$/g, ''),
    unit: 'W', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 50000,
    staleAfterS: 120, hot: true,
    group: 'power',
  },
  'fan_speed': {
    key: 'fan_speed', displayName: 'Fan Speed'.replace(/^'|'$/g, ''),
    unit: 'rpm', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 30000,
    staleAfterS: 120, hot: false,
    group: 'thermal',
  },
  'fan_speed_pct': {
    key: 'fan_speed_pct', displayName: 'Fan Speed Percent'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 120, hot: false,
    group: 'thermal',
  },
  'psu_input_voltage': {
    key: 'psu_input_voltage', displayName: 'PSU Input Voltage'.replace(/^'|'$/g, ''),
    unit: 'V', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 600,
    staleAfterS: 120, hot: false,
    group: 'power',
  },
  'psu_output_power': {
    key: 'psu_output_power', displayName: 'PSU Output Power'.replace(/^'|'$/g, ''),
    unit: 'W', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 5000,
    staleAfterS: 120, hot: false,
    group: 'power',
  },
  'psu_state': {
    key: 'psu_state', displayName: 'PSU State'.replace(/^'|'$/g, ''),
    unit: 'bool', valueType: 'bool',
    aggregation: 'last',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'power',
  },
  'energy_consumed': {
    key: 'energy_consumed', displayName: 'Energy Consumed'.replace(/^'|'$/g, ''),
    unit: 'kWh', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 600, hot: false,
    group: 'power',
  },
  'if_admin_state': {
    key: 'if_admin_state', displayName: 'Interface Admin State'.replace(/^'|'$/g, ''),
    unit: 'bool', valueType: 'bool',
    aggregation: 'last',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_oper_state': {
    key: 'if_oper_state', displayName: 'Interface Oper State'.replace(/^'|'$/g, ''),
    unit: 'bool', valueType: 'bool',
    aggregation: 'last',
    minValid: null,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_speed': {
    key: 'if_speed', displayName: 'Interface Speed'.replace(/^'|'$/g, ''),
    unit: 'bps', valueType: 'gauge',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 3600, hot: false,
    group: 'interfaces',
  },
  'if_in_octets': {
    key: 'if_in_octets', displayName: 'Interface In Octets'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_out_octets': {
    key: 'if_out_octets', displayName: 'Interface Out Octets'.replace(/^'|'$/g, ''),
    unit: 'B', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_in_bps': {
    key: 'if_in_bps', displayName: 'Interface In Throughput'.replace(/^'|'$/g, ''),
    unit: 'bps', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_out_bps': {
    key: 'if_out_bps', displayName: 'Interface Out Throughput'.replace(/^'|'$/g, ''),
    unit: 'bps', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_in_errors': {
    key: 'if_in_errors', displayName: 'Interface In Errors'.replace(/^'|'$/g, ''),
    unit: 'count', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_out_errors': {
    key: 'if_out_errors', displayName: 'Interface Out Errors'.replace(/^'|'$/g, ''),
    unit: 'count', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_in_discards': {
    key: 'if_in_discards', displayName: 'Interface In Discards'.replace(/^'|'$/g, ''),
    unit: 'count', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_out_discards': {
    key: 'if_out_discards', displayName: 'Interface Out Discards'.replace(/^'|'$/g, ''),
    unit: 'count', valueType: 'counter',
    aggregation: 'last',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'if_in_error_rate': {
    key: 'if_in_error_rate', displayName: 'Interface In Error Rate'.replace(/^'|'$/g, ''),
    unit: 'count_per_s', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: null,
    staleAfterS: 300, hot: false,
    group: 'interfaces',
  },
  'ambient_temperature': {
    key: 'ambient_temperature', displayName: 'Ambient Temperature'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'max',
    minValid: -40,
    maxValid: 90,
    staleAfterS: 120, hot: true,
    group: 'environment',
  },
  'relative_humidity': {
    key: 'relative_humidity', displayName: 'Relative Humidity'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 120, hot: true,
    group: 'environment',
  },
  'dew_point': {
    key: 'dew_point', displayName: 'Dew Point'.replace(/^'|'$/g, ''),
    unit: 'C', valueType: 'gauge',
    aggregation: 'avg',
    minValid: -40,
    maxValid: 60,
    staleAfterS: 120, hot: false,
    group: 'environment',
  },
  'airflow': {
    key: 'airflow', displayName: 'Airflow'.replace(/^'|'$/g, ''),
    unit: 'pct', valueType: 'gauge',
    aggregation: 'avg',
    minValid: 0,
    maxValid: 100,
    staleAfterS: 120, hot: false,
    group: 'environment',
  },
};

export const HOT_METRICS = (Object.keys(METRICS) as MetricKey[])
  .filter((k) => METRICS[k].hot);
