# Code generated by contracts/codegen.py. DO NOT EDIT.
"""Mapping profile groups, generated from contracts/mappings/*."""
from __future__ import annotations


#: protocol -> the group names a poll profile may select.
#:
#: SNMP is the only entry because MetricGroups is read in exactly
#: one place in the collector, the SNMP adapter. gNMI subscribes
#: from its own mapping file, BACnet reads its object map and
#: Modbus its register templates - a group named on a profile used
#: by any of those selects nothing at all.
MAPPING_GROUPS: dict[str, tuple[str, ...]] = {
    "snmp": ("system", "interfaces", "host_resources", "entity_sensors", "network_sensors", "pdu_apc", "pdu_raritan", "network_cisco",),
}

#: Every group name known to any protocol.
ALL_GROUPS = frozenset(g for gs in MAPPING_GROUPS.values() for g in gs)
