# Code generated by contracts/codegen.py. DO NOT EDIT.
"""Canonical metric registry, generated from contracts/metrics/registry.yaml."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class MetricDef:
    key: str
    display_name: str
    unit: str
    value_type: str
    aggregation: str
    min_valid: float | None
    max_valid: float | None
    stale_after_s: int
    hot: bool
    group: str
    rate_of: str | None
    rate_scale: float
    device_types: tuple[str, ...]


METRICS: dict[str, MetricDef] = {
    "sys_uptime": MetricDef(
        key="sys_uptime", display_name="System Uptime", unit="s",
        value_type="counter", aggregation="last",
        min_valid=0, max_valid=None,
        stale_after_s=300, hot=False,
        group="system", rate_of=None, rate_scale=1.0,
        device_types=(),
    ),
    "reachable": MetricDef(
        key="reachable", display_name="Reachable", unit="bool",
        value_type="bool", aggregation="last",
        min_valid=None, max_valid=None,
        stale_after_s=300, hot=True,
        group="system", rate_of=None, rate_scale=1.0,
        device_types=(),
    ),
    "poll_latency": MetricDef(
        key="poll_latency", display_name="Poll Latency", unit="ms",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=60000,
        stale_after_s=300, hot=False,
        group="system", rate_of=None, rate_scale=1.0,
        device_types=(),
    ),
    "cpu_utilization": MetricDef(
        key="cpu_utilization", display_name="CPU Utilization", unit="pct",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=100,
        stale_after_s=120, hot=True,
        group="compute", rate_of=None, rate_scale=1.0,
        device_types=("server", "switch", "router", "firewall", "load_balancer",),
    ),
    "cpu_temperature": MetricDef(
        key="cpu_temperature", display_name="CPU Temperature", unit="C",
        value_type="gauge", aggregation="max",
        min_valid=-20, max_valid=130,
        stale_after_s=120, hot=True,
        group="thermal", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "memory_utilization": MetricDef(
        key="memory_utilization", display_name="Memory Utilization", unit="pct",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=100,
        stale_after_s=120, hot=True,
        group="compute", rate_of=None, rate_scale=1.0,
        device_types=("server", "switch", "router", "firewall", "load_balancer",),
    ),
    "memory_used": MetricDef(
        key="memory_used", display_name="Memory Used", unit="B",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=None,
        stale_after_s=120, hot=False,
        group="compute", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "memory_total": MetricDef(
        key="memory_total", display_name="Memory Total", unit="B",
        value_type="gauge", aggregation="last",
        min_valid=0, max_valid=None,
        stale_after_s=3600, hot=False,
        group="compute", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "memory_available": MetricDef(
        key="memory_available", display_name="Memory Available", unit="B",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=None,
        stale_after_s=120, hot=False,
        group="compute", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "disk_utilization": MetricDef(
        key="disk_utilization", display_name="Disk Utilization", unit="pct",
        value_type="gauge", aggregation="max",
        min_valid=0, max_valid=100,
        stale_after_s=300, hot=False,
        group="compute", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "disk_used": MetricDef(
        key="disk_used", display_name="Disk Used", unit="B",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=None,
        stale_after_s=300, hot=False,
        group="compute", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "disk_total": MetricDef(
        key="disk_total", display_name="Disk Total", unit="B",
        value_type="gauge", aggregation="last",
        min_valid=0, max_valid=None,
        stale_after_s=3600, hot=False,
        group="compute", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "inlet_temperature": MetricDef(
        key="inlet_temperature", display_name="Inlet Temperature", unit="C",
        value_type="gauge", aggregation="max",
        min_valid=-20, max_valid=80,
        stale_after_s=120, hot=True,
        group="thermal", rate_of=None, rate_scale=1.0,
        device_types=("server", "switch", "router", "sensor",),
    ),
    "exhaust_temperature": MetricDef(
        key="exhaust_temperature", display_name="Exhaust Temperature", unit="C",
        value_type="gauge", aggregation="max",
        min_valid=-20, max_valid=100,
        stale_after_s=120, hot=False,
        group="thermal", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "power_draw": MetricDef(
        key="power_draw", display_name="Power Draw", unit="W",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=50000,
        stale_after_s=120, hot=True,
        group="power", rate_of=None, rate_scale=1.0,
        device_types=("server", "switch", "router", "firewall", "load_balancer", "pdu", "cdu", "crah",),
    ),
    "fan_speed": MetricDef(
        key="fan_speed", display_name="Fan Speed", unit="rpm",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=30000,
        stale_after_s=120, hot=False,
        group="thermal", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "fan_speed_pct": MetricDef(
        key="fan_speed_pct", display_name="Fan Speed Percent", unit="pct",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=100,
        stale_after_s=120, hot=False,
        group="thermal", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "psu_input_voltage": MetricDef(
        key="psu_input_voltage", display_name="PSU Input Voltage", unit="V",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=600,
        stale_after_s=120, hot=False,
        group="power", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "psu_output_power": MetricDef(
        key="psu_output_power", display_name="PSU Output Power", unit="W",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=5000,
        stale_after_s=120, hot=False,
        group="power", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "psu_state": MetricDef(
        key="psu_state", display_name="PSU State", unit="bool",
        value_type="bool", aggregation="last",
        min_valid=None, max_valid=None,
        stale_after_s=300, hot=False,
        group="power", rate_of=None, rate_scale=1.0,
        device_types=("server",),
    ),
    "energy_consumed": MetricDef(
        key="energy_consumed", display_name="Energy Consumed", unit="kWh",
        value_type="counter", aggregation="last",
        min_valid=0, max_valid=None,
        stale_after_s=600, hot=False,
        group="power", rate_of=None, rate_scale=1.0,
        device_types=("server", "pdu",),
    ),
    "if_admin_state": MetricDef(
        key="if_admin_state", display_name="Interface Admin State", unit="bool",
        value_type="bool", aggregation="last",
        min_valid=None, max_valid=None,
        stale_after_s=300, hot=False,
        group="interfaces", rate_of=None, rate_scale=1.0,
        device_types=("switch", "router", "server", "firewall", "load_balancer", "oob_switch",),
    ),
    "if_oper_state": MetricDef(
        key="if_oper_state", display_name="Interface Oper State", unit="bool",
        value_type="bool", aggregation="last",
        min_valid=None, max_valid=None,
        stale_after_s=300, hot=False,
        group="interfaces", rate_of=None, rate_scale=1.0,
        device_types=("switch", "router", "server", "firewall", "load_balancer", "oob_switch",),
    ),
    "if_speed": MetricDef(
        key="if_speed", display_name="Interface Speed", unit="bps",
        value_type="gauge", aggregation="last",
        min_valid=0, max_valid=None,
        stale_after_s=3600, hot=False,
        group="interfaces", rate_of=None, rate_scale=1.0,
        device_types=("switch", "router", "server", "firewall", "load_balancer", "oob_switch",),
    ),
    "if_in_octets": MetricDef(
        key="if_in_octets", display_name="Interface In Octets", unit="B",
        value_type="counter", aggregation="last",
        min_valid=0, max_valid=None,
        stale_after_s=300, hot=False,
        group="interfaces", rate_of=None, rate_scale=1.0,
        device_types=("switch", "router", "server", "firewall", "load_balancer", "oob_switch",),
    ),
    "if_out_octets": MetricDef(
        key="if_out_octets", display_name="Interface Out Octets", unit="B",
        value_type="counter", aggregation="last",
        min_valid=0, max_valid=None,
        stale_after_s=300, hot=False,
        group="interfaces", rate_of=None, rate_scale=1.0,
        device_types=("switch", "router", "server", "firewall", "load_balancer", "oob_switch",),
    ),
    "if_in_bps": MetricDef(
        key="if_in_bps", display_name="Interface In Throughput", unit="bps",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=None,
        stale_after_s=300, hot=False,
        group="interfaces", rate_of='if_in_octets', rate_scale=8.0,
        device_types=("switch", "router", "server", "firewall", "load_balancer", "oob_switch",),
    ),
    "if_out_bps": MetricDef(
        key="if_out_bps", display_name="Interface Out Throughput", unit="bps",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=None,
        stale_after_s=300, hot=False,
        group="interfaces", rate_of='if_out_octets', rate_scale=8.0,
        device_types=("switch", "router", "server", "firewall", "load_balancer", "oob_switch",),
    ),
    "if_in_errors": MetricDef(
        key="if_in_errors", display_name="Interface In Errors", unit="count",
        value_type="counter", aggregation="last",
        min_valid=0, max_valid=None,
        stale_after_s=300, hot=False,
        group="interfaces", rate_of=None, rate_scale=1.0,
        device_types=("switch", "router", "server", "firewall", "load_balancer", "oob_switch",),
    ),
    "if_out_errors": MetricDef(
        key="if_out_errors", display_name="Interface Out Errors", unit="count",
        value_type="counter", aggregation="last",
        min_valid=0, max_valid=None,
        stale_after_s=300, hot=False,
        group="interfaces", rate_of=None, rate_scale=1.0,
        device_types=("switch", "router", "server", "firewall", "load_balancer", "oob_switch",),
    ),
    "if_in_discards": MetricDef(
        key="if_in_discards", display_name="Interface In Discards", unit="count",
        value_type="counter", aggregation="last",
        min_valid=0, max_valid=None,
        stale_after_s=300, hot=False,
        group="interfaces", rate_of=None, rate_scale=1.0,
        device_types=("switch", "router", "server", "firewall", "load_balancer", "oob_switch",),
    ),
    "if_out_discards": MetricDef(
        key="if_out_discards", display_name="Interface Out Discards", unit="count",
        value_type="counter", aggregation="last",
        min_valid=0, max_valid=None,
        stale_after_s=300, hot=False,
        group="interfaces", rate_of=None, rate_scale=1.0,
        device_types=("switch", "router", "server", "firewall", "load_balancer", "oob_switch",),
    ),
    "if_in_error_rate": MetricDef(
        key="if_in_error_rate", display_name="Interface In Error Rate", unit="count_per_s",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=None,
        stale_after_s=300, hot=False,
        group="interfaces", rate_of='if_in_errors', rate_scale=1.0,
        device_types=("switch", "router", "server", "firewall", "load_balancer", "oob_switch",),
    ),
    "ambient_temperature": MetricDef(
        key="ambient_temperature", display_name="Ambient Temperature", unit="C",
        value_type="gauge", aggregation="max",
        min_valid=-40, max_valid=90,
        stale_after_s=120, hot=True,
        group="environment", rate_of=None, rate_scale=1.0,
        device_types=("sensor",),
    ),
    "relative_humidity": MetricDef(
        key="relative_humidity", display_name="Relative Humidity", unit="pct",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=100,
        stale_after_s=120, hot=True,
        group="environment", rate_of=None, rate_scale=1.0,
        device_types=("sensor",),
    ),
    "dew_point": MetricDef(
        key="dew_point", display_name="Dew Point", unit="C",
        value_type="gauge", aggregation="avg",
        min_valid=-40, max_valid=60,
        stale_after_s=120, hot=False,
        group="environment", rate_of=None, rate_scale=1.0,
        device_types=("sensor",),
    ),
    "airflow": MetricDef(
        key="airflow", display_name="Airflow", unit="pct",
        value_type="gauge", aggregation="avg",
        min_valid=0, max_valid=100,
        stale_after_s=120, hot=False,
        group="environment", rate_of=None, rate_scale=1.0,
        device_types=("sensor", "crah",),
    ),
}

HOT_METRICS = tuple(k for k, m in METRICS.items() if m.hot)
COUNTER_METRICS = tuple(k for k, m in METRICS.items() if m.value_type == 'counter')
# counter key -> the gauge key its rate is written to
RATE_TARGETS = {m.rate_of: k for k, m in METRICS.items() if m.rate_of}
